### ISSUE TITLE
inputField runs forever

### ISSUE THREAD

**Issue by freeall** [cronvel/terminal-kit#10]
I would expect this program to terminate

``` js
var term = require('terminal-kit').terminal

term('enter something: ')
term.inputField(function (err, input) {
  term('should terminate')
  terminate()
})

function terminate () {
  term.grabInput(false)
  // should terminate app now?
}
```

But it never does. Not until the user manually closes it. Is this expected behaviour?

**Comment by cronvel** [comment]
Hi, 

I'm aware of this issue, but there isn't much to do. The lib is not to blame for this, that's the way Node.js deals with stdin that cause this. You should explicitly close the app at the end of the `terminate()` function. 

You can replace your `terminate()` function by:
```
function terminate() {
  term.processExit() ;
}
```
This will turn grabInput off, perform some cleanup and exit.
`term.processExit()` accepts an exit code as argument.

**Comment by freeall** [comment]
Hi,

Thanks for your answer. You are right that I could do `process.exit()`, but that doesn't seem like the best solution.

I'm not sure you're right about the `stdin`. but I don't think that's entirely correct. If you look at this `readline` example:

``` js
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('Press enter', (answer) => {
  rl.close();
});
```

It terminates after you press enter. I'm guessing it could be fixed in `terminal-kit` by closing the input stream when the user does `grabInput(false)`, or am I wrong?

**Comment by cronvel** [comment]
Yes, closing the input stream would terminate the process.

When grab-input is turned off, it only removes the input stream listener. It is possible to turn grab-input on later, so it doesn't make sense to close the stream.

**Comment by freeall** [comment]
To me it should be possible to do it the same way that `readline` does. It feels a little off that after I am done reading input I now have to use `process.exit` when I want to, at some point, close the program. 

Imagine I'm making a program where I ask the user for something, and at some point my program starts to download a file. Now it becomes scary if I closed the program before the download stream was done.

**Comment by cronvel** [comment]
Well, you should know when your app should be closed or not ;)

Seriously, if at some point this is a problem for you, you may consider using [async-kit's async.exit()](https://github.com/cronvel/async-kit#ref.async.exit). That will help you to cleanly exit your app.

Whenever I get some time, I will explore the readline() code source to see if there is some tricks to achieve that cleanly. Closing stdin is not an option.
