### ISSUE TITLE
"Key is not Defined"

### ISSUE THREAD

**Issue by JonFranchi** [cronvel/terminal-kit#100]
I used the first boilerplate example from the linked tutorial and it seems some core functionality is producing unexpected results right out of the box:

var term = require( 'terminal-kit' ).terminal ;
```

term.grabInput() ;

term.on( 'key' , function( name , matches , data ) {  
    console.log( "'key' event:" , name ) ;

    // Detect CTRL-C and exit 'manually'
    if ( key === 'CTRL_C' ) { process.exit() ; }
} ) ;
```

`ReferenceError: key is not defined` if I run it and hit any key.

I am using Mac OS firstly, but what am I missing here?  I haven't tried to do anything but execute the boilerplate example after installing the npm package.

**Comment by cronvel** [comment]
@JonFranchi The `key` variable should be replaced by `name`.
Where did you find this sample code? (so it will eventually get fixed)

**Comment by JonFranchi** [comment]
The examples link referenced at the top of your readme: http://blog.soulserv.net/tag/terminal/
