### ISSUE TITLE
cant set cwd in termianl 

### ISSUE THREAD

**Issue by amitgilad3** [cronvel/terminal-kit#107]
Hello, 
iv been trying to create a terminal instance add start it in a different dir but i seems to stay in the directory i run my code from 

```
var path = require( 'path' ) ;
var { execSync } = require('child_process');
var term = require( 'terminal-kit' ).terminal ;
let str = ''
term.cwd( 'file:/' + '/tmp/test' ) ;

term.on( 'key' , function( key ) {

  if(key === 'ENTER'){
    // console.log('enter')
    //return execSync(str);

    term(execSync(str))
    str = ''
  }
  if(key === 'q' || key === 'CTRL_C'){
    process.exit() ;
  }
  //str = str + key
  term(key)
  str = str + key
} ) ;

term.grabInput() ;
```

every time i run pwd inside the terminal i still get the directory in which i run the script and not the place set in cwd.
im pretty sure im doing something, any assistance would be appreciated

**Comment by cronvel** [comment]
Hi @amitgilad3,
You are misunderstanding what `term.cwd()` is for. It does **NOT** change the current working directory, instead it informs the terminal of the current working directory. The terminal application *MAY* use it for different things, like displaying the path in the status bar, for example Gnome-Terminal will use that path as the CWD for the new tab when the Ctrl-Shift-T shortcut is typed, and so on...

Terminal, TTY and shell are three different things that people tends to mix up.

For doing what you need, you should use `process.chdir()` as usual.
