### ISSUE TITLE
individual markup for menu items

### ISSUE THREAD

**Issue by critcap** [cronvel/terminal-kit#110]
Hello there, I really enjoy the deep functions of terminal kit. A feature what I would like is the ability to use individual [markup](https://github.com/cronvel/terminal-kit/blob/f26d3344e5c079f95de78902d0c49b8a3ea50e2f/doc/markup.md#top) for items in menu instead of just selected and unselected options

**Comment by cronvel** [comment]
@critcap Which menu are you using?
For example, for `term.singleLineMenu()` you could replace in the item array `"my menu entry"` by `term.str( "^Rmy ^Gmenu ^Bentry" )` to have it written using red, green and blue.

**Comment by critcap** [comment]
Oh snap, I just tried it with the markup in the string without the term.str() part.
Thank you!
