### ISSUE TITLE
Table is not rendered completely

### ISSUE THREAD

**Issue by TimvdEijnden** [cronvel/terminal-kit#111]
When using a large number of columns the top of the table is not rendered.
I tried to use the table in a project, but am unable to because of this.
I modified the sample to show the issue, see code below.

Here's a gif of the issue:

![screencast 2020-03-19 15-35-54](https://user-images.githubusercontent.com/951290/77078924-8a848280-69f7-11ea-8584-40b16b53bb5f.gif)

```js
const contents = new Array(50).fill(['first', 'second']);

term.table( [
	[ 'This is' , 'not shown' ] ,
	...contents
] , {
	//hasBorder: false ,
	contentHasMarkup: true ,
	borderChars: 'lightRounded' ,
	borderAttr: { color: 'blue' } ,
	textAttr: { bgColor: 'default' } ,
	//textAttr: { bgColor: 'black' } ,
	firstCellTextAttr: { bgColor: 'blue' } ,
	firstRowTextAttr: { bgColor: 'gray' } ,
	firstColumnTextAttr: { bgColor: 'red' } ,
	//checkerEvenCellTextAttr: { bgColor: 'gray' } ,
	//evenCellTextAttr: { bgColor: 'gray' } ,
	//evenRowTextAttr: { bgColor: 'gray' } ,
	//evenColumnTextAttr: { bgColor: 'gray' } ,
	width: 60 ,
	//height: 20 ,
	fit: true , // Activate all expand/shrink + wordWrap
	//expandToWidth: true , shrinkToWidth: true , expandToHeight: true , shrinkToHeight: true , wordWrap: true ,
}
) ;
```

Issue occurs in: Terminal, iTerm2 and vsCode.

I'm using ZSH as shell.

**Comment by cronvel** [comment]
@TimvdEijnden Erf... I know why it does that... Will fix it as soon as I have some free time...

**Comment by TimvdEijnden** [comment]
If you know where I should look I might be able to help out.

**Comment by cronvel** [comment]
@TimvdEijnden It should work now as of v1.35.2. Thanks for reporting.

**Comment by TimvdEijnden** [comment]
True it works!
