### ISSUE TITLE
Extra output for mouse events

### ISSUE THREAD

**Issue by Tayyab12308** [cronvel/terminal-kit#112]
My code looks like this:
```
function handleTerminalClick() { 
  term.grabInput({ mouse: "button" })
  term.on("mouse", name => {
    if (name === "MOUSE_RIGHT_BUTTON_RELEASED" ||
        name === "MOUSE_LEFT_BUTTON_RELEASED")
        console.log(progress.next().value)
      ;
  })
}
```

After using ```grabInput({mouse: 'button'})```  each mouse button released action spits stuff into the term (e.g. ```0;55;3M0;55;3m<whatever was actually supposed to be printed>```)
I've also attached a picture of what the output looks like.

I'm running this in the regular terminal that comes with macOs

<img width="1065" alt="Screen Shot 2020-04-11 at 10 42 48 PM" src="https://user-images.githubusercontent.com/41034857/79059307-5858f000-7c46-11ea-9338-520b2817f94d.png">

**Comment by cronvel** [comment]
@Tayyab12308 Can you try to run `./sample/all-event-test.js` and press some mouse buttons? And eventually make a screenshot of it? 
To be honest, I need a MacOS maintainer, I don't own any Apple device, and sadly terminals are never 100% compatible, each of them needs some tweaking.
Also run `./sample/detect-terminal-test.js`, it will not detect the correct terminal since there is no MacOS terminal profile, but it will help me to know what is the base (fallback) profile used.

**Comment by cronvel** [comment]
@Tayyab12308 From what I see, your terminal send commands using the Mouse SGR protocol, which is supported by Terminal Kit, but for some reason, it doesn't detect it... Very strange. So I'm waiting for your response.
Does it work inside iTerm2?

**Comment by Tayyab12308** [comment]
I went to the project directory and tried to run 
```./sample/all-event-test.js``` 
and it printed out
```zsh: no such file or directory: ./sample/all-event-test.js``` 
and when I ran 
```./sample/detect-terminal-test.js```
 it said 
```zsh: no such file or directory: ./sample/detect-terminal-test.js```

**Comment by cronvel** [comment]
@Tayyab12308 Both files exist, check your install ;)

**Comment by Tayyab12308** [comment]
Ahh yes lol I just had to hop in my node_modules directory

heres the output for ```./sample/all-event-test.js```
<img width="1008" alt="Screen Shot 2020-04-12 at 12 06 01 PM" src="https://user-images.githubusercontent.com/41034857/79073741-27b09f00-7cb6-11ea-9216-5e9482690fe1.png">

and heres ```./sample/detect-terminal-test.js```
<img width="1012" alt="Screen Shot 2020-04-12 at 12 06 39 PM" src="https://user-images.githubusercontent.com/41034857/79073742-28493580-7cb6-11ea-9e3d-31bc4dfad409.png">

**Comment by cronvel** [comment]
@Tayyab12308 The first screenshot show that mouse is correctly detected, and do not output anything on the terminal. (The second screenshot exposes a bug, but it's not relevant in your case)

Are you sure there isn't another part of your code that is reading STDIN, and then writing it back to STDOUT?  Once you activate mouse handling, the terminal send escape sequences to STDIN containing mouse event, and another part of your code may be confused. That's my only guest so far! ;)

**Comment by Tayyab12308** [comment]
Hmm maybe because I was running my app with the command ```node -i -e "$(< script.js)"``` when I ran it with ``` node script.js``` it worked fine

**Comment by cronvel** [comment]
@Tayyab12308 Yes, that's it. Like I said, the events are sent by your terminal through STDIN. ;)
