### ISSUE TITLE
terminal-kit with xterm.js 

### ISSUE THREAD

**Issue by ppacory** [cronvel/terminal-kit#113]
Is there a way to use terminal-kit with xterm.js in a browser, how to do it ?

**Comment by cronvel** [comment]
Assuming *xterm.js* is a web-based terminal, compatible with *Xterm*, you can use Terminal Kit just the way you would with any other terminal. *Xterm* is the default/fallback config in Terminal Kit.
It all depends on the *Xterm.js* compatibility with the real *Xterm*.

**Comment by ppacory** [comment]
here is a start of code : bundle with browserify to use require

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "browserify index.js -o bundle.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "terminal-kit": "^1.35.2",
    "xterm": "^4.5.0"
  }
}
```
index.html

```
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <div id="terminal-container"></div>
    <script src="./bundle.js"></script>
  </body>
</html>
```

index.js
```
const Terminal = require('xterm').Terminal;

const term = new Terminal({});
term.isTTY = true;
window.process = process;
process.stdout = process.stdin = process.stderr = term; 

var termKIT = require( 'terminal-kit' ).terminal ;
termKIT('hello World!!!')
```

The result is 
error : TypeError: term.stdout.on is not a function (Terminal.js)
```
else if ( term.stdout.isTTY ) { term.stdout.on( 'resize' , onResize.bind( term ) ) ; }  
```

**Comment by cronvel** [comment]
@ppacory BTW stdout is supposed to be a Node.js stream interface. Terminal Kit works with streams.
