### ISSUE TITLE
inputField() returns immediatly when used through SSH with Powershell 

### ISSUE THREAD

**Issue by alexpado** [cronvel/terminal-kit#116]
Hi,

When logging in through SSH with powershell and executing my script, inputField() ends immediately.

Code used:
```js
#!/usr/bin/env node
const terminal = require('terminal-kit').terminal;

function terminate() {
	terminal.grabInput( false ) ;
	setTimeout( function() { process.exit() } , 100 ) ;
}

terminal.grabInput( { mouse: 'button' } ) ;

terminal.on( 'key' , function( name , matches , data ) {
	console.log( "'key' event:" , name ) ;
	if ( name === 'CTRL_C' ) { terminate() ; }
} ) ;

terminal.magenta( "Type something: " ) ;
terminal.inputField((e, i) => {
    terminal.green("You typed %s !\n", i);
});
```

### Tested

| Use Case                         | Issue ? |
|----------------------------------|---------|
| Git Bash For Windows             | No      |
| SSH through Git Bash For Windows | No      |
| Powershell                       | No      |
| SSH through Powershell           | Yes     |

### Console output when the issue happen

```
Type something: 'key' event: ESCAPE
'key' event: [
'key' event: 1
'key' event: 9
'key' event: ;
'key' event: 1
'key' event: 7
'key' event: R
You typed (undefined) !
```

**Comment by cronvel** [comment]
Can you exec the file `./sample/detect-terminal-test.js` for your 4 use cases?
`.inputField()` always ask the terminal for the cursor location, the sequence you obtained is the terminal response, but for some reason it is not detected as a cursor location response.

**Comment by alexpado** [comment]
Sorry for the wait, all the files are attached to this message.

[powershell.txt](https://github.com/cronvel/terminal-kit/files/4780240/powershell.txt)
[powershell-ssh.txt](https://github.com/cronvel/terminal-kit/files/4780241/powershell-ssh.txt)
[git-bash.txt](https://github.com/cronvel/terminal-kit/files/4780242/git-bash.txt)
[git-bash-ssh.txt](https://github.com/cronvel/terminal-kit/files/4780243/git-bash-ssh.txt)

**Comment by cronvel** [comment]
@alexpado Thanks for the reports, I will look into it as soon as possible.

**Comment by alexpado** [comment]
The issue is partially resolved. The escape sequence is still captured, but the method don't end directly, I can type what I want:

```
$ node .
Type something: 'key' event: ESCAPE
'key' event: [
'key' event: 5
'key' event: 2
'key' event: ;
'key' event: 1
'key' event: 7
'key' event: R

> 'key' event: Y
Y'key' event: e
e'key' event: s
s'key' event: ENTER
You typed Yes !
```

Every other use cases don't capture the escape sequence. But a script shouldn't show everything like this anyway :)

Output of `./sample/detect-terminal-test-.js` : 
```
== Environment variable ==

$TERM: xterm-256color
$COLORTERM: (undefined)
$VTE_VERSION: (undefined)


== Using simple terminal guessing ==

.guessTerminal(): {"isTTY":true,"isSSH":true,"appId":"xterm-256color","safe":false,"generic":"xterm-256color"}
Terminal name: (undefined)
Terminal app ID: (undefined)
Generic terminal: xterm-256color
Config file: xterm-256color.generic.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: FAILED (Error: .getCursorLocation() timed out)
Support for palette request: FAILED (Error: .getColor() timed out)
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK


== Using advanced terminal detection ==

Can't get parent terminal info: Error [Error]: SSH connection detected, .getParentTerminalInfo() is useless in this context.
    at Object.exports.getParentTerminalInfo (/home/akio/source/node_modules/terminal-kit/lib/detectTerminal.js:179:11)
    at detect (/home/akio/source/node_modules/terminal-kit/sample/detect-terminal-test.js:99:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
Terminal name: (undefined)
Terminal app ID: (undefined)
Generic terminal: xterm-256color
Config file: xterm-256color.generic.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: FAILED (Error: .getCursorLocation() timed out)
Support for palette request: FAILED (Error: .getColor() timed out)
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK
```

**Comment by cronvel** [comment]
@alexpado I'm sorry, but it looks like I can't do anything for that use-case. The fact it looks partially resolved comes from another fix I made for another issue, a fallback specifically made for terminal that don't support cursor location request.
Here, something is messing with the input somewhere in between, splitting escape sequences. And the fact that `htop` has issues too is not a good news.

**Comment by alexpado** [comment]
I think I shouldn't be too surprised as it's a Microsoft product...

Anyway, thanks for your time, I'll use Git Bash the time being :)
