### ISSUE TITLE
Display issue when delete CJK fonts in inputField

### ISSUE THREAD

**Issue by halsn** [cronvel/terminal-kit#117]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13534265/84890791-70793f80-b0cd-11ea-91c0-a8a526a5413c.gif)

OS: Windows 10
Terminal: wsl-terminal

When I input Chinese and delete them, the inputField still display some of the content, but the value of inputField is empty already. 

I think that's because the Chinese font is full-width font, but I don't how to fix it 😐

**Comment by cronvel** [comment]
@halsn Terminal-kit is supposed to have partial full-width support, at least in most case. 
However since I'm not chinese I can't say it's extensively tested. On my Linux box, `.inputField()` seems to support full-width char: I can copy-paste chinese chars, then delete them, it does not break anything, so I'm a bit confused...

Can you give me more detail?

* When you hit backspace, does it delete one full-width char for each backspace?
* Can you paste here a string that break the inputField, so I can test it on my side?
* Does your terminal handle full-width correctly when running other CLI programS?

It could be some trouble with the full-width unicode range detection (but again, the unicode ranges are supposed to be good).

**Comment by halsn** [comment]
> @halsn Terminal-kit is supposed to have partial full-width support, at least in most case.
> However since I'm not chinese I can't say it's extensively tested. On my Linux box, `.inputField()` seems to support full-width char: I can copy-paste chinese chars, then delete them, it does not break anything, so I'm a bit confused...
> 
> Can you give me more detail?
> 
> * When you hit backspace, does it delete one full-width char for each backspace?
> * Can you paste here a string that break the inputField, so I can test it on my side?
> * Does your terminal handle full-width correctly when running other CLI programS?
> 
> It could be some trouble with the full-width unicode range detection (but again, the unicode ranges are supposed to be good).

@cronvel Thanks for your explanation. 

1. When I hit backspace, it exactly deletes one full-width char of the content in inputField. But the appearance is like that it just delete half of the char.
2. Please check '中文'. In Chinese, the word '中文' has two chars, but as Chinese is full-width char, so '中文' is equal to four English chars.
3. I use wsl-terminal, terminal for windows 10 WSL, to run the test code. For other CLI programs, such as vim, it looks correctly when delete full-width chars.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13534265/84971630-bc6cc880-b14f-11ea-91ca-84a9e4da180c.gif)

For this gif, I test the appearance in vim, the chars are '中文', and I hit backspace two times. Everything is ok.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13534265/84971697-e3c39580-b14f-11ea-825d-56bcc3a514ac.gif)

For this gif, I test the appearance in inputField, the chars are '中文', and I hit backspace two times, but it still lefts '中' on the input.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/13534265/84971793-179ebb00-b150-11ea-8a9f-2b3f8d1bea25.gif)

For this gif, I change the terminal to windows 10 CMD and test the appearance in inputField. Same result as the above gif.

**Comment by cronvel** [comment]
Hi @halsn, I'm starting to understand the issue...

When Terminal Kit want to delete a char backward, it sends the *left* escape sequence, followed by the *delete* escape sequence, it is usually the string `\x1b[1D\x1b[1P`.

It seems that moving left when the previous character is full-width doesn't align with the char's first cell as expected. 

Just published the v1.35.4 which should fix the issue, tell me if it works for you (it works for me), so we can close the issue.

Thanks for reporting! ;)

**Comment by halsn** [comment]
@cronvel Thanks for your work 🙌

I have tested on my side, but it still has some issues.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13534265/85090705-5ac46100-b218-11ea-9bc1-13893bb6f20f.gif)

For this gif, I input '中文字符‘(4 chars in Chinese) on inputField, and delete them from the end. Everything is ok.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13534265/85090804-995a1b80-b218-11ea-88e5-48af7d843c41.gif)

For this gif, I input '中文字符' again and hit left arrow two times to move the cursor to char '字', then hit backspace two times. It lefts two spaces on the left of the inputField. The inputField displays something like '    字符', but what I except is only '字符'.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/13534265/85091134-55b3e180-b219-11ea-9361-084082f9d386.gif)

For this gif, I do the same action as first gif, but this time I changed to neovim built-in terminal. After I hit backspace four times, it left '\<ff\>\<ff\>' on inputField. I think it may be an issue of neovim, but I have no idea about this and hope to get your help :)

**Comment by cronvel** [comment]
@halsn Ok, it should be fixed. It looks like terminals do not care at all about the size of a char: *deleting one char* is in fact *deleting only one cell* whatever the content, a thing I didn't know until today.
Again, thanks for reporting, and I hope that v1.35.7 finally fix that issue.
For *neovim* try again and tell me, but I'm not sure this is a Terminal Kit issue.

**Comment by halsn** [comment]
@cronvel I have tested on CMD, PowerShell, windows terminal, wsl-terminal, neovim build-in terminal on windows 10, and everything is ok 🙌

We can close this issue right now, really thanks for your work 👍
