### ISSUE TITLE
Scrolling text

### ISSUE THREAD

**Issue by ThatTonybo** [cronvel/terminal-kit#118]
I'm building a small chat interface and I'm looking to "scroll" the messages up when a message hits the last line of the console **minus 3**, so further messages won't overwrite it and will scroll up nicely. Is there any way to do this easily?
I'm already using raw mode if that's any difference.

**Comment by cronvel** [comment]
@ThatTonybo There multiple way of doing this.

The simplest/low-level/documented way is to use [.scrollingRegion()](https://github.com/cronvel/terminal-kit/blob/master/doc/low-level.md#moving-the-cursor).

Or you can use the [Document Model](https://github.com/cronvel/terminal-kit/blob/master/doc/document-model.md) but it's not documented ATM. You can find your way by running various demo script you can found inside `./sample/document/*.js`. You would use an InlineInput and TextBox widget for that.

**Comment by ThatTonybo** [comment]
Thanks for the input. With platform compatibility in mind, which of these would be the best choice to use?

**Comment by cronvel** [comment]
@ThatTonybo Windows terminals are terrible anyway, so I can't say for sure it will work on it. Both methods are usually fine on all Linux terminal and OSX iTerm2.
I would say "choose the method you prefer".
If you want a full-blown terminal app, go for the document model if you are not afraid of undocumented API ^^ Despite the warning, the API is 99% stable.

**Comment by ThatTonybo** [comment]
Thanks for the tips. Might go with the doc model API as it looks appealing.
Any idea when the docs would be done?

**Comment by cronvel** [comment]
@ThatTonybo It takes time to write the doc, and sadly, Terminal Kit does not pay my bills, so it depends solely on my free time.
But if peoples start using it, I guess the urge to write it down will make it happen... ^^

**Comment by cronvel** [comment]
@ThatTonybo I have improved the documentation on [TextBox](https://github.com/cronvel/terminal-kit/blob/master/doc/document-model.md#ref.TextBox) and other things.

**Comment by cronvel** [comment]
@ThatTonybo Documentation on [InlineInput](https://github.com/cronvel/terminal-kit/blob/master/doc/InlineInput.md) added.
Hope this help.
