### ISSUE TITLE
Layout with formatted textbox

### ISSUE THREAD

**Issue by Grevinnan** [cronvel/terminal-kit#119]
Hello, first up I really like where you are going with this lib. I'm building a CLI for interacting with BitBucket through their REST API. I've started using terminal-kit (with the Document API) for building a UI, and I've run into a few issues:

1. Currently I'm using a layout with a single row with a ColumnMenu on the left (a list of files) and on the right is where I want the content of the currently selected file to go. I tried using a TextBox as the content, alas it does not seem to work well with the layout, it does not fill up the layout, I have to manually set the width/height of the TextBox which is not very elegant. I tried using the Text-class also but that one has issues with word/line wrap.

2. My purpose is to add syntax highlighting to the shown files in the content. I tried using 
[cli-highlight](https://www.npmjs.com/package/cli-highlight) and it works when I just use the output directly in the terminal-kit terminal, i.e. "terminal(highlightedText)". But I have not found a way to use it with the TextBox in the layout, it just prints the color escape-codes as text or similar. Do you have any idea on how to accomplish this? I peeked a bit at the TextBuffer and ScreenBuffer, I'm guessing I have to "inject" the text there somehow.

Here is some [experiment-code](https://github.com/Grevinnan/bbq/blob/repo_show/src/commands/repo_cmds/show.ts#L115) if that helps.

**Comment by cronvel** [comment]
@Grevinnan Hi, I confirm that TextBox is the way to go. Also there is no advanced mechanism at the moment for a Layout to force its children to adapt. It could be a great improvement, but I will have to look into it. Layout is *very* experimental at the moment.

As for using the output of a program full of ansi code, it's a missing feature. I didn't forecasted such a use, and I realize that it could be pretty common, so I will add it to my TODO.

**Comment by cronvel** [comment]
@Grevinnan Hi again,
You can run/have a look at this sample code: `./sample/document/text-box-test.js`.
I just added support for ANSI source-text, it should fix your (2). Use the option `contentHasMarkup: 'ansi'`.
Tell me if it solve that part.

**Comment by Grevinnan** [comment]
Thanks for the quick reply!

I tested your fix, it works when you initialize it but when you use setContent() later it does not, so halfway there perhaps.
Today I actually found a workaround with cli-highlight, wrapping some small functions that surrounded the highlighted parts with tkits markup-syntax instead of generating color escape codes, allowing me to use tkit "as intended". I'm not sure which way is better atm, but it would be nice to have both options. Only downside right now is I have to escape the tkit-carets so that they do not interfere.

Regarding (1), I actually found a way to make Text work for me, although I had to implement linewrap myself (Not sure it is very elegant, I had to get the width/height of the buffer from textBox.inputDst.width/height, as outputWidth did not really work). I'm not sure what the difference is, but Text seems to adapt to the layout "naturally". Perhaps it will be a bit tricky if I want to add a cursor or something to the Text-element if I need that, I will see. I guess on paper TextBox is a better fit, but perhaps I prefer a bit of inconvenience to avoid having to set the width/height myself :) .

I will try to wrap this in some sort of class which I can reuse. Text worked better with Layout, I'm trying to use as little layout-manipulation as possible and use widthPercent/heightPercent as much as possible :) . I found it was not so complicated to implement simple scrolling with the Text-element.

I realize layouts are a bit experimental, I don't plan on having any outrageously complicated interfaces so hopefully they will suffice.

**Comment by cronvel** [comment]
@Grevinnan Have you used `textBox.setContent( text, 'ansi' )` ? The second argument `ansi` should inform `.setContent()` that it contains ANSI code. Sorry, it's not documented yet (new in v1.35.10) and I forgot to tell you.

Also I insist that TextBox is the way to go. ;)
I can have a look tomorrow to see if the fix is easy, updating size automatically from Layout.
If things go well, it could be a 15-30 minutes fix (I hope so).
Also TextBox support scrollbar out of the box, which is great plus.

What is wrong with line-wrapping in TextBox? It should be OK, never seen a bug there... Any screenshot?

**Comment by Grevinnan** [comment]
Ah yes, when I entered 'ansi' there also it worked fine.

Sorry, a bit of a misunderstanding, I meant that there was no linewrapping in the Text-element, that was why I had to implement it.
I will give the TextBox  a go, will probably be better long term :). What is the distinction between the Text and TextBox element with regard to their purpose anyway? Is the Text-element more "low-level", i.e. a base class or similar?

**Comment by cronvel** [comment]
@Grevinnan Ok, some new features as of v1.35.11:

* All elements can specify a new option *autoWidth* and *autoHeight* to adjust width/height to the parent Container size
* TextBox inside a Layout/Container auto-adjust itself on Container resizing, when created with *autoWidth* or *autoHeight*
* `./sample/auto-resized-text-box-in-layout-test.js` demonstrate it and should be what you need

I hope it covers all your needs.
Text is more for *floating text*, and is the base class for Button, it is better for one-line text (but supports multi-line if the userland provide an array of line as *content*).
TextBox is backed by a TextBuffer and so has better support for per character attributes, and supports scrolling, line/word-wrapping and more. It's also the base class for EditableTextBox.

**Comment by cronvel** [comment]
Also, if it's a concern for you, even if not documented yet, Layout will be backward compatible anyway.

**Comment by Grevinnan** [comment]
I tried it, it seems to work fine! I tried resizing and things like that, seems to work like a charm. Thanks for the quick fixes.
