### ISSUE TITLE
process.env.TERM may be undefined on windows

### ISSUE THREAD

**Issue by KnisterPeter** [cronvel/terminal-kit#12]
Hi,

since `process.env.TERM`could be undefined terminal-kit will fail on `process.env.TERM.toLowerCase()`.
This happens in termkit.js line 96.

**Comment by cronvel** [comment]
Hi, thanks for reporting. It should be fixed now as of terminal-kit@0.24.14.

Can you tell me in which case TERM is undefined? SSH?
Without TERM, it fallback to a restricted set of xterm escape sequences, which is the standard the most used, but it is usually better if the terminal is known.

**Comment by KnisterPeter** [comment]
I was running my test cases on appveyor and there TERM was undefined.
Maybe they have a bit strange ENV setup.

**Comment by cronvel** [comment]
Ok, thanks, tell me if it works for you now! ;)

**Comment by KnisterPeter** [comment]
Thanks, its fine now :+1:
