### ISSUE TITLE
How to update content?

### ISSUE THREAD

**Issue by axed** [cronvel/terminal-kit#123]
Hello everyone,
i have a bit of trouble finding out how to update an `Element`'s content, let's say a `TextTable`'s `cellContents`.
Based on the _documentation_ an `Element`'s draw function should not have to be called explicitly, yet i cannot find any clue about a method that updates a `TextTable`'s `cellContents`.
In my tests i have done thus far, i've tried to update the `cellContents` via a timeout, like this:
```javascript
const TerminalKit = require('terminal-kit')
const term = TerminalKit.terminal
const document = term.createDocument()

const cellContents = [
  ['a1', 'b1', 'c1'],
  ['a2', 'b2', 'c2']
]

global.termkitElements = {
  mainLayout: new TerminalKit.Layout({
    parent: document,
    boxChars: 'single',
    layout: {
      id: 'mainLayout',
      y: 0,
      widthPercent: 100,
      heightPercent: 100,
      rows: [{
        id: 'header',
        height: 10,
        columns: [
          { id: 'namesList', width: 20 }
        ]
      }, {
        id: 'body',
        columns: [
          { id: 'logScreen' }
        ]
      }]
    }
  }),
  namesListTable: new TerminalKit.TextTable({
    parent: document.elements.namesList,
    hasBorder: false,
    cellContents
  })
}

setTimeout(() => {
 // failed attempt #1:
 //  trying to change the cells in place
 myCellContents.push([1, 2, 3, 4])
 // failed attempt #2
 // directly update the Element's data
  const update = [
    ['a1', 'b1', 'c1'],
    ['a2', 'b2', 'c2'],
    ['a3', 'b3', 'c3'],
    ['a4', 'b4', 'c4']
  ]
  global.termkitElements.namesListTable.cellContents = update
  global.termkitElements.namesListTable.redraw()
  document.redraw()
}, 2000)
```

What is the correct or intended way to update Text, TextBoxes, and TextTable then?

**Comment by cronvel** [comment]
@axed For all elements supporting it, you should do it with [`Element#setContent(content,[hasMarkup])`](https://github.com/cronvel/terminal-kit/blob/master/doc/Element.md#ref.Element.setContent).

TextBox can do it out of the box, it is the base class of EditableTextBox.
Text was meant to have static content, it is the base class of numerous more complex widget, and thus more complex behavior must be done using higher level widget.

TextTable is actually static too, but it could be dynamic in the future, but I will look if a quick fix is somehow possible.

Meanwhile, `textTable.textBoxes[y][x]` give you access to each cell TextBoxes, which can have dynamic content. But at the table level, the layout will not be updated to fit the content size. For that you can call `textTable.computeCells()` then call `textTable.draw()` manually. It should do the trick.

**Comment by cronvel** [comment]
@axed  As of v1.43.0, I fixed things so that Text can now use `.setContent()`, and TextTable has a new method [`.setCellContent()`](https://github.com/cronvel/terminal-kit/blob/master/doc/TextTable.md#ref.TextTable.setCellContent) that does for you what you need.

Tell me if it does the job ;)

**Comment by cronvel** [comment]
@axed Any feedback before I close the issue?
