### ISSUE TITLE
Passively detect scrolling

### ISSUE THREAD

**Issue by Richienb** [cronvel/terminal-kit#125]
At the moment, when using `terminal.grabInput({mouse: "button"})` and `terminal.on("mouse", ...)`, scroll events are captured and then prevented from happening. Is there a way to allow such events to continue propagating?

**Comment by cronvel** [comment]
@Richienb No there isn't, once the app tells the terminal that it intercepts mouse event, default behavior is prevented. If the terminal doesn't provide another way to scroll to its history buffer, you can't.

**Comment by Richienb** [comment]
@cronvel Is there a way to detect if the terminal **can** be scrolled?

**Comment by cronvel** [comment]
@Richienb No there isn't. This isn't part of what is called the TTY.

**Comment by Richienb** [comment]
@cronvel Would there be a way to detect if the terminal actually scrolled on the scroll event?

**Comment by cronvel** [comment]
@Richienb No you can't, and there is no scroll event (at the terminal level).
You can detect the mouse wheel event.
