### ISSUE TITLE
InputField autoComplete strip prefix

### ISSUE THREAD

**Issue by frissdiegurke** [cronvel/terminal-kit#13]
It would be great to have an option to strip a prefix from auto-complete items.
For example if you want to build a shell-like environment, `cmd fil` could be auto-completed to `cmd file0` or `cmd file1`. Within the items shown for completion, the `cmd ` prefix should be stripped out.

**Comment by cronvel** [comment]
Do you know that the `autoComplete` option ca be a function? 
It's in the second example of the [inputField() doc](https://github.com/cronvel/terminal-kit#ref.inputField).

Your feature request is interesting, but probably a bit too high level for the lib scope.

**Comment by cronvel** [comment]
In fact, it was already possible, admittedly not clearly documented.

As of v0.24.26, I added a fourth argument to `termkit.autoComplete` to ease the process.
The second example of the `inputField()` doc can be rewritten this way for your use-case:

```js
var termkit = require( 'terminal-kit' ) ;
var term = termkit.terminal ;

var autoCompleter = function autoCompleter( inputString , callback )
{  
    var index = inputString.lastIndexOf( ' ' ) ;
    var prefix = inputString.slice( 0 , index + 1 ) ;
    inputString = inputString.slice( index + 1 ) ;
    
    fs.readdir( __dirname , function( error , files ) {
        callback( undefined , termkit.autoComplete( files , inputString , true , prefix ) ) ;
    } ) ;
} ;
    
term( 'Choose a file: ' ) ;

term.inputField(
    { autoComplete: autoCompleter , autoCompleteMenu: true } ,
    function( error , input ) {
        if ( error )
        {
            term.red.bold( "\nAn error occurs: " + error + "\n" ) ;
        }
        else
        {
            term.green( "\nYour file is '%s'\n" , input ) ;
        }
        
        process.exit() ;
    }
) ;
```

Hope it helps!

**Comment by frissdiegurke** [comment]
Great! With that `prefix` property on arrays, it works like a charm!
Thanks and keep up the great work :thumbsup:
