### ISSUE TITLE
Container class key event for scroll up/down implementation seems different with wheel event

### ISSUE THREAD

**Issue by drunkhacker** [cronvel/terminal-kit#130]
While `Container.prototype.onWheel` calls `this.scroll` function with parameter calculated using `this.viewportHeight`, 
`Container.prototype.onKey` calls scroll function with value of `this.textAreaHeight`. 

And it seems that `textAreaHeight` is not defined for Container class. I think `onKey` also should call `scroll` function using `viewportWidth(Height)`

**Comment by cronvel** [comment]
@drunkhacker Thanks for the catch, your PR is merged ;)
