### ISSUE TITLE
Is it possible to paginate data (like git log) with terminal-kit?

### ISSUE THREAD

**Issue by laurent22** [cronvel/terminal-kit#135]
I'm looking to create a utility a bit like "git log" that would display a lot of data, but paginated, so the user can press "space" to go to the next page. I guess it's possible to do this with terminal-kit, but I'm wondering if there's already some utility that could be used, and that would do most of this automatically?

**Comment by cronvel** [comment]
Hi,

There are two ways to do it.

One is low-level, using [.scrollUp()/.scrollDown()/.scrollingRegion()](https://github.com/cronvel/terminal-kit/blob/master/doc/low-level.md#moving-the-cursor).

The other is high-level, using the [document-model](https://github.com/cronvel/terminal-kit/blob/master/doc/document-model.md), but the documentation is still in progress. You would use the [TextBox widget](https://github.com/cronvel/terminal-kit/blob/master/doc/TextBox.md).

You can look at sample codes inside `sample/document/` and more precisely this [text logger](https://github.com/cronvel/terminal-kit/blob/master/sample/document/text-box-logger-test.js). Document model fully supports the mouse out of the box.

**Comment by laurent22** [comment]
Thanks, I had missed the new document-model feature, that looks really good! I'll give a try to the TextBox widget and see if I can get it working.
