### ISSUE TITLE
Property 'table' does not exist on type 'Terminal'. (Typescript)

### ISSUE THREAD

**Issue by dogue** [cronvel/terminal-kit#137]
I'm using terminal-kit with typescript and everything has been working as expected, until I tried to create a table. For some reason it's telling me that the table method doesn't exist on the terminal object. I can create a table without issue outside of TS.

This seems to be specific to typescript. Any ideas? Terminal-kit was installed via NPM. `"terminal-kit": "^1.44.0"`

Edit for clarity: So far every other function in the module has worked flawlessly under typescript for me.

```typescript
private displaySinglePart( data :any ) :void {
    this.term.clear();
    this.term.table([
        [ 'Part #', 'Description', 'Quantity', 'Cost', 'List '],
        [ data.partNumber, data.description, data.quantity, data.cost, data.list ]
    ], {
        hasBorder: true,
        borderChars: 'light',
        borderAttr: { color: 'green' },
        width: 60
    })
}

**Comment by dogue** [comment]
It seems as if the table method was missed when `@types/terminal-kit` was written. Will try to get a pull request in to fix that on their end.

**Comment by cronvel** [comment]
Hi,
Sorry for that, but I do not maintain typescript. One contributor made it one day, but there is no maintainer for that. Any PR is welcome ;)

**Comment by hugo-cardoso** [comment]
Any updates about this?
