### ISSUE TITLE
Screen Dump

### ISSUE THREAD

**Issue by aurium** [cronvel/terminal-kit#14]
Allows to extract screen text data.

My use-case is testing some terminal interface. Other use-cases my be "term-screensavers"; Post written highlighters; Automation...

**Comment by cronvel** [comment]
Hi,

FYI there is no way to get the terminal internal buffer.

However, Terminal-kit has a feature that can achieve that: the ScreenBuffer.
It isn't documented right now, but it should be stable enough (the interface hasn't changed in 1 year, and I use it on some project).

You can look at the spaceship demo, in the `demo` folder run `./spaceship.js`, and then look how it works.

The ScreenBuffer is optimized, it only redraws cells that have changed. You can see the optimization in action in the spaceship demo, the stats tells you how many operations there are.

**Comment by aurium** [comment]
huum... May work for `terminal-kit` based software, like [config-template](https://github.com/alarner/config-template). Thanks!

**Comment by cronvel** [comment]
Only if the software use the ScreenBuffer, but config-template doesn't.

**Comment by cronvel** [comment]
@aurium I put a lot of effort documenting the [ScreenBuffer](https://github.com/cronvel/terminal-kit/blob/master/doc/screenbuffer.md) for the v1 (released yesterday). Happy coding! ;)
