### ISSUE TITLE
Form with select, only with keyboard

### ISSUE THREAD

**Issue by Grevinnan** [cronvel/terminal-kit#142]
I was experimenting with the form(i.e. as in the sample/document/form-test.js sample). I tried using the select-type and it works, but I could not find any way to use only the keyboard, i.e. I can use tab to switch focus to the select-element but I cannot find any key that opens the selection-box (I tried looking a bit in the code but I could not find anything about keybindings, maybe there aren't any specifically for the selection?). The mouse works, but I wondered if there is a way to get it to be usable with only the keyboard? Maybe It is easiest if I inject my own keyboard mappings into the form?

**Comment by cronvel** [comment]
@Grevinnan Thanks for reporting, there was some issue with the *focus* of widget inside `Form`, the `SelectList` didn't receive it correctly, so the keyboard event was firing on the parent. It's fixed as of v1.45.0. 
You have to use the enter/return key to open it.
"Tab" is used for cycling from one input to another, enter/return cycles too for input like single-line text, but not for `SelectList` anymore.
