### ISSUE TITLE
Emit as Menu selections are focused (but not submitted)?

### ISSUE THREAD

**Issue by NuSkooler** [cronvel/terminal-kit#143]
Is there an event emit I'm missing when menu (`ColumnMenu`, etc.) are selected but not submitted? I would like to update a `TextBox` as selections are navigated through and perform a different action when they are submitted.

**Comment by cronvel** [comment]
@NuSkooler `ColumnMenu` has no *selected item concept*, unlike `SelectList` (also there is no event for that anyway ATM).

I agree it could be useful, can you describe what you are trying to achieve with more details?

**Comment by NuSkooler** [comment]
@cronvel For my immediate purpose I plan on updating a descriptive `TextBox` as the user navigates through the `ColumnMenu` items. When they submit, I will lave the page.

If you have thoughts on _how_ it should be implemented I can submit a PR.

**Comment by cronvel** [comment]
@NuSkooler Ok, so I've added the 'itemFocus' event on all widget inheriting from BaseMenu.
To see it in action, just run/open the file `sample/document/column-menu-test.js`.
It's published as version v1.45.1.

Tell me if it does the job.

**Comment by NuSkooler** [comment]
@cronvel Thanks, this is exactly what I needed.
