### ISSUE TITLE
TextBox garbles ANSI

### ISSUE THREAD

**Issue by NuSkooler** [cronvel/terminal-kit#147]
Loading a valid ANSI file into a `TextBox` (e.g. with `setContent(ansiContents, 'ansi')`) garbles the image.

Example (Expected):
![image](https://user-images.githubusercontent.com/1509339/105660372-16710180-5e88-11eb-92d1-7eb92024f782.png)

In `TextBox`:
![image](https://user-images.githubusercontent.com/1509339/105660398-238df080-5e88-11eb-9495-1355edca9ca1.png)

See attached ANSI file (renamed to .txt).
[avatar.ans.txt](https://github.com/cronvel/terminal-kit/files/5864105/avatar.ans.txt)

**Comment by cronvel** [comment]
@NuSkooler Can you post the unicode version?

**Comment by NuSkooler** [comment]
[avatar_utf8.ans.txt](https://github.com/cronvel/terminal-kit/files/5868025/avatar_utf8.ans.txt)

Here you go

**Comment by cronvel** [comment]
@NuSkooler Found a bug in the parser, now it works.
