### ISSUE TITLE
TermKit.Text with contentHasMarkup: 'ansi'

### ISSUE THREAD

**Issue by NuSkooler** [cronvel/terminal-kit#153]
`TermKit.Text` using `contentHasMarkup: 'ansi'` within a document results in partial ESC sequences output.

It appears that the text is passed through `parseMarkup()` within `ScreenBuffer.put` vs `parseAnsi`. This results in `0x1b` being converted to a space/`0x20`.

**Comment by cronvel** [comment]
@NuSkooler Did the #147 patch fix it?

**Comment by NuSkooler** [comment]
@cronvel Unfortunately no. For whatever reason it doesn't appear to be going through the `parseAnsi` path but instead the `parseMarkup` path.

**Comment by cronvel** [comment]
@NuSkooler Ok I misread the issue.
Now it should work (v1.48.1).

**Comment by NuSkooler** [comment]
@cronvel That did the trick!
