### ISSUE TITLE
Terminalkit for mac.

### ISSUE THREAD

**Issue by Elie404** [cronvel/terminal-kit#154]
Hello,
There is a problem with Terminal Kit on Mac, it is impossible to erase carcaters and sometimes the controls go sideways. As you can see from the screenshot.

Is it possible to correct this?
cordially
Elie.

**Comment by Elie404** [comment]
![Capture d’écran 2021-02-16 à 21 11 33](https://user-images.githubusercontent.com/79168733/108118060-1686aa80-709e-11eb-8bbf-841f12a5b466.png)
This is the screen

**Comment by cronvel** [comment]
@Elie404 Hello,
Can you please execute `/sample/detect-terminal-test.js` and paste the output here?
Can you tell me which terminal app you use, and if SSH is involved?

**Comment by Elie404** [comment]
Hi,
Thanks for your reply. 
![Capture d’écran 2021-02-18 à 17 06 47](https://user-images.githubusercontent.com/79168733/108385166-b281f480-720b-11eb-8970-16825c4cd98f.png)
You want this?

**Comment by cronvel** [comment]
@Elie404 No I want the execution's output of this script! Run the script, copy and paste the output!

**Comment by imf** [comment]
Hi @cronvel I am having the same problems, with zsh.

Here is the output you were asking for: 

imf@krypton sample % node ./detect-terminal-test.js 

== OS and Environment Variables ==

Node version: v14.15.3
OS platform: darwin
OS type: Darwin
OS release: 20.2.0
OS version: Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
$TERM: xterm-256color
$COLORTERM: (undefined)
$VTE_VERSION: (undefined)
$TERM_PROGRAM: Apple_Terminal


== Using simple terminal guessing ==

.guessTerminal(): {"isTTY":true,"isSSH":false,"appId":"osx-256color","safe":true,"generic":"osx-256color"}
Terminal name: (undefined)
Terminal app ID: osx-256color
Generic terminal: osx-256color
Config file: osx-256color.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 41)
Support for palette request: OK
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK


== Using advanced terminal detection ==

.getParentTerminalInfo(): {"appId":"osx-256color","appName":"Terminal","pid":594,"safe":true}
Terminal name: (undefined)
Terminal app ID: osx-256color
Generic terminal: xterm-256color
Config file: osx-256color.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 41)
Support for palette request: OK
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK

**Comment by imf** [comment]
Also, fwiw, I see the same behavior in bash. I haven't tried this on a non-Apple-silicon Mac to see if it's somehow ARM-related (which would be odd but not unheard-of.) (Happy to test if that's of use.)

The behavior I'm seeing is that, in an input field, backspace doesn't result in the previously entered character being removed.

**Comment by imf** [comment]
Also, I'm super new to terminal-kit... Is it expected that multiline terminal output would "get dimmer"  as the lines go down?

You can see the effect I'm describing here: This multiline ASCII dinosaur is all in a term.bold.grey() block (but other formatting also had the dinosaur disappear:

term.bold.grey(`            __
           / _)
    .-^^^-/ /    
 __/       /
<__.|_|-|_|
`)

...produced this...

<img width="682" alt="Screen Shot 2021-03-05 at 5 36 13 PM" src="https://user-images.githubusercontent.com/47360/110190672-4f7e8900-7dd9-11eb-981e-81ec13a3df4c.png">

Happy to open a separate issue if that's a separate thing, and I'm good working around it too!

**Comment by imf** [comment]
Also, same 'no backspace' (and text gradient-y) behavior in iTerm:

imf@krypton Brindisi % node node_modules/terminal-kit/sample/detect-terminal-test.js

== OS and Environment Variables ==

Node version: v14.15.3
OS platform: darwin
OS type: Darwin
OS release: 20.2.0
OS version: Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
$TERM: xterm-256color
$COLORTERM: truecolor
$VTE_VERSION: (undefined)
$TERM_PROGRAM: iTerm.app


== Using simple terminal guessing ==

.guessTerminal(): {"isTTY":true,"isSSH":false,"appId":"osx-256color","safe":true,"generic":"osx-256color"}
Terminal name: (undefined)
Terminal app ID: osx-256color
Generic terminal: osx-256color
Config file: osx-256color.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 25)
Support for palette request: OK
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK


== Using advanced terminal detection ==

.getParentTerminalInfo(): {"appId":"osx-256color","appName":"iTerm2","pid":90325,"safe":true}
Terminal name: (undefined)
Terminal app ID: osx-256color
Generic terminal: xterm-256color
Config file: osx-256color.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 25)
Support for palette request: OK
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK

imf@krypton Brindisi %

**Comment by cronvel** [comment]
@imf Thanks for reporting.
Please run also run the script `sample/key-test.js`, type the backspace key and screenshot the output.

**Comment by imf** [comment]
Thanks @cronvel 

And I did end up testing on Intel hardware, with the same behavior. Note, however, that ^H (manually entered) does "the right thing".

Output below...

Key: DELETE , length: 6 , all matches: [ 'DELETE', 'BACKSPACE' ] , is character: false , codepoint:  , buffer: <Buffer 7f>

<img width="892" alt="Screen Shot 2021-03-07 at 6 31 41 PM" src="https://user-images.githubusercontent.com/47360/110266821-7d97d080-7f73-11eb-9691-6c8ce013e72b.png">

**Comment by imf** [comment]
Reading the docs a little more, I think I see what's happening here... The Backspace key is being interpreted as Delete. I can confirm that, if I move around with the arrow keys, and then hit backspace, it has the default "delete" behavior of deleting the character to the right of the cursor.

**Comment by imf** [comment]
Is there a resolution for this?

**Comment by cronvel** [comment]
@imf Hi,

Sorry to be late, I have tons of works IRL.
The problem comes from this file: `terminal-kit/lib/termconfig/osx-256color.js`, this line: `DELETE: '\x7f'` should be replaced by `BACKSPACE: '\x7f'`.

The change is fairly trivial, **BUT** the thing is that I don't own a MacOS to test what I'm doing. This file was written by a Mac user, and it's hard for me to know if it was a mistake on its end or if there are some conflicts between different Mac terminal apps.

Any dedicated **OSX maintainer** is more than welcome on this project.

From your report, we can see that your terminal is not sending `^H` (which is charcode `\x08`) but `\x7f`. Linux terminals send either `\x08` or `\x7f` for BACKSPACE, so this is not surprising.

If we want to solve this, I need you to test both DELETE and BACKSPACE keys using `sample/key-test.js` on the most common OSX terminals (at least the one shipped with OSX and iTerm2). Also some terminals offer an option for changing what those keys are generating, so be careful to have the default behavior in your terminal preferences.

**Comment by Elie404** [comment]
Bonjour désolée pour mon absence,
J'ai vu que vous étiez français j'utilise depuis tout à l'heure google traduction mais je ne comprend rien 😅

Du coup pouvez vous m'expliquer ce que vous souhaitez s'il vous plaît?

Elie.

**Comment by cronvel** [comment]
@Elie404 Je veux simplement que vous exécutiez le programme `/sample/detect-terminal-test.js` et afficher la sortie. Toutefois la version v2.0.6 devrait régler le problème, donc pensez à d'abord à mettre à jour Terminal-kit.

**Comment by cronvel** [comment]
@imf Hi again, version v2.0.6 published just now should fix this problem, it has been tested by @dangilkerson on Terminal.app and iTerm2.

**Comment by Elie404** [comment]
```
== OS and Environment Variables ==

Node version: v14.15.5
OS platform: darwin
OS type: Darwin
OS release: 19.6.0
OS version: Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
$TERM: xterm-256color
$COLORTERM: (undefined)
$VTE_VERSION: (undefined)
$TERM_PROGRAM: Apple_Terminal


== Using simple terminal guessing ==

.guessTerminal(): {"isTTY":true,"isSSH":false,"appId":"osx-256color","safe":true,"generic":"osx-256color"}
Terminal name: (undefined)
Terminal app ID: osx-256color
Generic terminal: osx-256color
Config file: osx-256color.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 24)
Support for palette request: OK
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK


== Using advanced terminal detection ==

.getParentTerminalInfo(): {"appId":"osx-256color","appName":"Terminal","pid":34376,"safe":true}
Terminal name: (undefined)
Terminal app ID: osx-256color
Generic terminal: xterm-256color
Config file: osx-256color.js

Support for delta escape sequence: OK
Support for 256 colors: OK
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 24)
Support for palette request: OK
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK
```

J'ai fait la mise à jour je suis bien sous 2.0.6 mais toujours rien.

**Comment by cronvel** [comment]
@Elie404 Fait la même manipulation que j'ai demandé sur ce thread, lance le programme `sample/key-test.js` et appuie sur BACKSPACE puis DELETE, et poste-moi la sortie du programme.

Sinon tu peux aussi te mettre à **iTerm2** qui est mieux supporté par Termnial Kit (car tous les utilisateurs Mac sont dessus) et qui est de toute façon mieux que le terminal de base.

**Comment by Elie404** [comment]
![Capture d’écran 2021-03-21 à 13 25 07](https://user-images.githubusercontent.com/79168733/111904801-fbb2a780-8a48-11eb-92bb-757f006a0a99.png)

Voilà!

**Comment by cronvel** [comment]
@Elie404 Houlà, t'es sûr que t'es sur la dernière version? Parce qu'elle inclut [ce patch](https://github.com/cronvel/terminal-kit/pull/162) qui s'assure que `x7f` est détecté comme BACKSPACE uniquement, alors que sur ton screenshot on voit bien qu'il y a ambiguïté avec DELETE.

**Comment by Elie404** [comment]
Vous auriez une commande pour connaitre la version?

**Comment by cronvel** [comment]
@Elie404 `npm ls`.

**Comment by Elie404** [comment]
![image](https://user-images.githubusercontent.com/79168733/111912386-9b802d80-8a69-11eb-9590-103c74142cf2.png)

oulah

**Comment by Elie404** [comment]
![image](https://user-images.githubusercontent.com/79168733/111912600-ac7d6e80-8a6a-11eb-8b3f-db635818be90.png)
au final ça a réglé le problème 1 des 2 applications n'était pas à jour c'est pour cela que ça n'avait rien changé.

La 2.0.7 règle bien les problèmes 
Merci beaucoup pour votre aide.

**Comment by imf** [comment]
Now it was my turn to be away! (I feel you on 'work IRL taking time'. Thanks for all the love you give to this really terrific library.)

I can also verify this fixed!

Happy to help test things that need Mac OS testing... (And sorry from being away from the thread for so long.)

**Comment by cronvel** [comment]
@imf Thanks!
