### ISSUE TITLE
Any references to run the term.inputField in a loop

### ISSUE THREAD

**Issue by dineshkumar02** [cronvel/terminal-kit#157]
Hi Everyone,

This terminal-kit is an awesome framework, and we are trying to build a solution using this framework.
But, we are facing issues, on how we run the term.inputField after every time the user submit his request.

After processing the user request, we print the response on the console and will give the prompt back to him/her to
take more inputs.

Would you please share any document references or examples for the same.

**Comment by cronvel** [comment]
@dineshkumar02 Which issue? This should work well. I suggest you to use an async function with a loop, awaiting for `.inputField( options ).promise`. Got it working on various situation.

**Comment by dineshkumar02** [comment]
@cronvel , thanks for suggestions. I have made the function call in the callback, and it is working fine.
