### ISSUE TITLE
Best way to implement a fixed input box with scrolling log behind?

### ISSUE THREAD

**Issue by Tmp2k** [cronvel/terminal-kit#161]
I'm creating a serial monitor in Node and I'd like the incoming serial data to scroll up the screen as it comes in (easy). But I'd like a text input at the bottom of the screen that fills up with text as typed but only sends to serial when enter is pressed. (input needs to allow cursor movement, delete backspace etc.

It would also be nice to add some toggle options or a menu etc, also fixed on screen either top or bottom.

I've been looking at the document features, but I didn't know if there was an easier way of just creating an input etc and having it render at a fixed position on screen (e.g. the bottom row) why the usual console just scrolls behind.

**Comment by cronvel** [comment]
@Tmp2k Hi, I'm a bit late, but have a look on sample code inside the `sample/document/` directory. There is all you need. 

It's part of the *document model*, it's not documented much at the moment, but it's stable anyway. There are a lot of widgets, with mouse support (if your terminal support it), configurable key bindings, and more. `TextBox` can support scrolling (with scrollbar), `EditableTextBox` is suitable for multi-line input, or `InlineInput` for one-line input.
There are lot of menu types: `ColumnMenu`, `DropDownMenu`, `SelectList`, ... 

If you want something simpler, just use `term.inputField()` for your input (but it's what I call the *inline mode*, and it's not made to work with concurrent widgets).
