### ISSUE TITLE
how to stop loader

### ISSUE THREAD

**Issue by tanay-pingalkar** [cronvel/terminal-kit#163]
i am using terminal.spinner() and i want to stop this loader after an sync.. function, my code is like
``` javascript
terminal.spinner();
 const spawn = spawnSync(splitted[0], splitted.splice(1));
// i want spinner to stop here 
```
please help!!!

**Comment by cronvel** [comment]
@tanay-pingalkar Hi, you can do this:

```js
var spinner = terminal.spinner();
// Do some stuffs...
spinner.destroy();
```

Also, you may probably know that nothing can happen at all if you are only doing synchronous things in between.

**Comment by tanay-pingalkar** [comment]
`TypeError: spinner.destroy is not a function`
im using typescript and i installed types of terminal-kit, but it shows that `spinner wont exist on type Terminal`, i ignored it and continue but then my application throw that error

**Comment by tanay-pingalkar** [comment]
> `TypeError: spinner.destroy is not a function`
> im using typescript and i installed types of terminal-kit, but it shows that `spinner wont exist on type Terminal`, i ignored it and continue but then my application throw that error

`spinner.distroy` worked btw thanks, but now it is showing ` Error: .getCursorLocation() timed out`

**Comment by cronvel** [comment]
@tanay-pingalkar You are probably using a terminal that doesn't support cursor location query.
Please comment in the relevant issue about it. 
You are probably a Windows user, so try installing a modern terminal (or use WSL). I can't help you much on that, I don't own any Windows.

**Comment by alxpereira** [comment]
Better answer
https://github.com/cronvel/terminal-kit/issues/129
