### ISSUE TITLE
"Unexpected token ." in /lib/TextBuffer.js:1594

### ISSUE THREAD

**Issue by amulchinock** [cronvel/terminal-kit#167]
When attempting to use Terminal Kit's `table()` method, I am getting the following error from Node:

```
UnhandledPromiseRejectionWarning:[redacted]/node_modules/terminal-kit/lib/TextBuffer.js:1594
TextBuffer.prototype.object2attr = function( attrObject , colorNameToIndex = this.palette?.colorNameToIndex , legacyColor = false ) {
                                                                                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    
    ...
```

Doing some digging - it appears this might be a bug caused by a typo, introduced in 55665156fe0347fa13accf689accec467ff779bd. At a cursory glance, it looks like `colorNameToIndex = this.palette?.colorNameToIndex` should actually read `colorNameToIndex = this.palette.colorNameToIndex`.

I've added a comment on the appropriate line https://github.com/cronvel/terminal-kit/commit/55665156fe0347fa13accf689accec467ff779bd#r50383603

I had a look to see if there were any other instances of errors like this, and couldn't see any.

If someone can confirm whether this is indeed intentional or not, I'm more than happy to make a PR to address this. 👍

**Comment by cronvel** [comment]
@amulchinock You are using a Node.js version that is not supported. Starting from v2.0.0, you need at least Node 14.15 (Fermium LTS), if you are using Node 12, use the last v1 version (v1.49.3 at the time that comment is written).

**Comment by amulchinock** [comment]
Testing with `lts/fermium -> v14.16.1` and it works as expected. I hadn't come across the optional chain syntax before (looks very handy), so I ended up jumping to the wrong conclusion it seems.

I learned something - so, thanks for pointing me in the right direction 😄
