### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by bradennapier** [cronvel/terminal-kit#18]
any plans to make this return promises instead of the standard callback?

**Comment by cronvel** [comment]
Hi,
That's not planned for the v1.

**Comment by LoganDark** [comment]
@cronvel really??

**Comment by devzsolt** [comment]
It would be really useful

**Comment by cronvel** [comment]
@LoganDark @devzsolt @bradennapier It will be done once I got some time dedicated to the project.

**Comment by cronvel** [comment]
@LoganDark @devzsolt @bradennapier It's not yet documented, but almost everything now support promises, as of v1.19.

E.g.:
```js
input = await term.inputField().promise ;
choice = await term.singleColumnMenu( items ).promise ;
choice = await term.yesOrNo().promise ;
cursorLoc = await term.getCursorLocation() ;
color = await term.getColor( register ) ;
palette = await term.getPalette() ;
// ...
```

**Comment by LoganDark** [comment]
Okay, thanks

**Comment by cronvel** [comment]
@LoganDark @devzsolt @bradennapier The documentation is updated.

**Comment by devzsolt** [comment]
Awesome, thank you @cronvel!
