### ISSUE TITLE
A high severity vulnerability introduced in your package

### ISSUE THREAD

**Issue by paimon0715** [cronvel/terminal-kit#182]
Hi ,@cronvel, I’d like to report a vulnerability issue in your package:
### Issue Description
   A high severity vulnerability [**SNYK-JS-TREEKIT-1077068**](https://snyk.io/vuln/SNYK-JS-TREEKIT-1077068) detected in package **tree-kit<0.7.0** is directly referenced by **_terminal-kit@1.49.3_**. We noticed that such a vulnerability has been removed since _**terminal-kit@2.0.5**_.
  
   However, terminal-kit's popular previous version **_terminal-kit@1.49.3_**  ([11,739 downloads per week](https://www.npmjs.com/package/terminal-kit/v/1.49.3?activeTab=versions)) is still transitively referenced by a large amount of latest versions of active and popular downstream projects (about **259 downstream projects**, e.g., graphqurl 1.0.1, @haul-bundler/core 0.23.0, @haul-bundler/cli 0.23.0, foundation-cli 2.2.6, joplin 2.1.2, @coveops/cli@0.17.0 and rest-query@0.65.3,etc.).
As such, issue [**SNYK-JS-TREEKIT-1077068**](https://snyk.io/vuln/SNYK-JS-TREEKIT-1077068) can be propagated into these downstream projects and expose security threats to them.
   
   These projects cannot easily upgrade **terminal-kit** from version **_1.49.3_** to _**(>=2.0.5)**. _ For instance, **_terminal-kit@1.49.3_** is introduced into the above projects via the following package dependency paths:
(1) `@coveops/cli@0.17.0 ➔ tramway-command@1.2.0 ➔ terminal-kit@1.49.3 ➔ tree-kit@0.6.2`
(2) `rest-query@0.65.3 ➔ logfella-client@1.2.3 ➔ terminal-kit@1.49.3 ➔ tree-kit@0.6.2`
    **......**
    
The projects such as **tramway-command** and **logfella-client**, which introduced terminal-kit@1.49.3, are not maintained anymore. These unmaintained packages can neither upgrade **terminal-kit** nor be easily migrated by the large amount of affected downstream projects.  
 On behalf the downstream users, could you help us remove the vulnerability from package terminal-kit@1.49.3?

### Suggested Solution

Since these unactive projects set a version constaint **1.49.\*** for **terminal-kit** on the above vulnerable dependency paths, if **terminal-kit** removes the vulnerability from 1.5.3 and releases a new patched version **_terminal-kit@1.49.4_**, such a vulnerability patch can be automatically propagated into the 259 affected downstream projects.

In **_terminal-kit@1.49.4_**, you can kindly try to perform the following upgrade:
       `tree-kit ^0.6.2 ➔ ^0.7.0`;  
**Note:**
**_tree-kit@0.7.0(>=0.7.0)_** has fixed the vulnerability ([**SNYK-JS-TREEKIT-1077068**](https://snyk.io/vuln/SNYK-JS-TREEKIT-1077068))

Thank you for your contributions.

Best regards,
Paimon

**Comment by cronvel** [comment]
Hi,

Thanks for your concern, but there is no vulnerability at all.

First, as the author of both packages, tree-kit's vulnerability was already a kind of misuse of said lib (not supposed to be feed by user input, don't even know how that could be useful), but well, I suppose we can't prevent people from doing it the other way around, hence the fix on tree-kit@0.7.0.

Terminal kit depends on tree-kit but don't use (and don't misuse) that part of code.

**So user on terminal-kit@1.49.3 are safe.** (at least, there is no known vulnerability at the moment).

However, if that false-positive is coming from some kind of automatic tool, maybe I will consider it. I understand the need for security, but frankly all those tools are constantly getting in the way for nothing. E.g. I wish npm would STOP those scary security reports on devDependencies, I have package needing Browserify for building, and they all display big warning at npm install time... at some point I will simply remove the devDependency and assume Browserify is installed on the dev (me) computer.

**Comment by paimon0715** [comment]
@cronvel Thanks for your feedback.
The vulnerbility reports came from those tools.
A large amount active downstream users of terminal-kit@1.49.3 (a very popular version, 11,739 downloads per week), would receive such security reports every build.
So if you can help fix this issue, such a vulnerability patch can be propagated into ten thousands of downstream projects,
which can indeed benefit the npm ecosystem.


Thanks again,

**Comment by paimon0715** [comment]
@cronvel Thanks for your help.

**Comment by cronvel** [comment]
@paimon0715 You're welcome ;)
