### ISSUE TITLE
 Physical keyboard input ignored by terminal

### ISSUE THREAD

**Issue by AusPrinzip** [cronvel/terminal-kit#190]
Once I start my nodejs program and execute `singleColumnMenu` or `singleLineMenu` my terminal does no longer respond to keyboard strokes.

````
async function promptAccount() {
  term.cyan('Chose the account from which to operate.\n');

  const { selectedIndex, selectedText } = await term.singleColumnMenu(
    ACCOUNTS,
    { cancelable: true }
  );
  ACCOUNT = selectedText;
  ACCOUNT_INDEX = selectedIndex;
  return ACCOUNT;
}
````

It seems as if terminal-kit would take over  and isolate the shell.

I am working on a macbook air 2020 (m1) with macOS Monterey.

**Comment by cronvel** [comment]
@AusPrinzip There is no bug, any widget requires to turn your terminal into what is called *raw mode* (internally, it calls `term.grabInput()`). Depending on *your* terminal, it *MAY* still short-circuit some shorthand, but you are basically on your own. That's how terminal application works whatever the lib or programming language you used.

E.g. If you want your terminal to exit on `Ctrl-C`, you have to listen for the *key* event and call `process.exit()`.

Also you can call `term.grabInput(false)` to return to the *cooked mode* you are familiar with. [See the doc](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.grabInput).

**Comment by AusPrinzip** [comment]
Excellent, I understand.

Thanks for the quick reply and great work!
