### ISSUE TITLE
support ESM

### ISSUE THREAD

**Issue by rudolfolah** [cronvel/terminal-kit#200]
There's an article here on how to do this: https://electerious.medium.com/from-commonjs-to-es-modules-how-to-modernize-your-node-js-app-ad8cdd4fb662

The steps seem to be:
1. `"type": "module"` to the `package.json`
2. convert all imports and exports
3. fix imports and exports

For the time being, the following snippet could be added to the README.md:

```javascript
import terminalKitPackage from 'terminal-kit';
const { terminal } = terminalKitPackage;
```

**Comment by hades3729** [comment]
Any news about this?

**Comment by cronvel** [comment]
... except that there are lazy require that cannot translate into ESM...

**Comment by mortezae** [comment]
If someone reaches here seeking for ESM, yes it is possible:
```js
import TK from 'terminal-kit'

const term = TK.terminal
term.red( 'Hello' )
```
