### ISSUE TITLE
drawImage( ... ) draws Image not until end of program.

### ISSUE THREAD

**Issue by Sayum24** [cronvel/terminal-kit#201]
When I want to draw an Image I want to stop the program, until the image is finished.

```js
const term = require('terminal-kit').terminal;
const getPixels = require("get-pixels")

drawImage();


console.log('Test123')

function drawImage(){
  term.drawImage("logo.png", {
  shrink: {
    width: 100,
    height: 100
  }
})

  return;
}
```
This code prints first `Test123` and then starts to print the image.
How can I change that?

**Comment by Sayum24** [comment]
Found this way to print in the program:
Make the function which calls the function to draw the Image into a async function.
```js
const term = require('terminal-kit').terminal;
const getPixels = require("get-pixels")

test();

async function drawImage() {
  await term.drawImage("logo.png", {
    shrink: {
      width: 50,
      height: 50
    }
  }, )

  return;
}

async function test(){
  console.log('before')
  await drawImage();
  console.log('after')
}
```

Is this the only way to make this happen?

**Comment by cronvel** [comment]
@Sayum24 
From the doc, you'll see that [.drawImage()](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.drawImage) is not sync. You have to pass a callback (old API) *OR* await for the returning promise.

In Javascript, async/await/promise are very common concept you should be familiar with.
