### ISSUE TITLE
Impossible to compile with pkg

### ISSUE THREAD

**Issue by el2zay** [cronvel/terminal-kit#205]
Hello,
I try to compile my script in executable with the pkg module but the problem is that at the time of launching the executable this error is displayed: 

![image](https://user-images.githubusercontent.com/79168733/169664780-9fe34b70-54dc-4284-9b2d-5eeb192dc0c6.png)

(Screen on macOS catalina)

I have this error only when there is terminal kit in my code when I remove it everything works again. 
I have no idea if the problem comes from terminal kit or from pkg which manages terminal kit badly.

**Comment by djkato** [comment]
I have the exact same issue, with no idea how to fix it. I opened an issue in PKGs github too but got ignored.
My issue on pkg: #vercel/pkg#1619
similliar ones:
#vercel/pkg#1018 
#nexe/nexe#509

This apparently helps, but I couldn't get it to work no matter what I tried: 
https://stackoverflow.com/a/56909415

**Comment by alexn-s** [comment]
+1

**Comment by Tonours** [comment]
Hello! I had the same issue, and i've been able to fixed it by adding the `terminal-kit` node_modules into the assets of pkg, as follow

```json
"pkg": {
    "assets": [
      "../../node_modules/terminal-kit/**/*"
    ]
  },
```
