### ISSUE TITLE
.fullscreen on Windows

### ISSUE THREAD

**Issue by ghandhikus** [cronvel/terminal-kit#207]
The `fullscreen` function should at least maximise the cmd as there is no option for the library to maximise it.

**Comment by cronvel** [comment]
@ghandhikus Maybe the name is confusing, but that option was never meant to make the *host* terminal application to go fullscreen.
It makes your CLI application use the whole area of the terminal using (if supported by your terminal) an *alternate buffer*.
I don't think Windows has a terminal with such feature.

I don't know Windows enough to provide an example, but if you know a bit of Linux, the correct use-case is for CLI application like *htop*, that uses the whole terminal, but when you quit it, it restores your shell command history.
