### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by ghandhikus** [cronvel/terminal-kit#208]
The `singleLineMenu` features paging but other menu options do not. I just happened to have a surprising amount of data sometimes. And even a `gridMenu` can't fit them all. Any chance for paging to be added to other menu options? I am currently working around it by just making paging myself but I feel like this feature should be built in.

**Comment by cronvel** [comment]
You may use the `ColumnMenu` of the *Document Model*, it's only partly documented, but it can be considered **stable**.
See the sample code located here: `./sample/document/column-menu-test.js`.
