### ISSUE TITLE
StringKit issue

### ISSUE THREAD

**Issue by Anas2001** [cronvel/terminal-kit#211]
I get this error with nodejs version 14.0.0

..../string-kit/lib/unicode.js:237
                return emojiWidthLookup.get( code ) ?? 2 ;
                                       ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)

**Comment by cronvel** [comment]
Hi,
Terminal-Kit requires at least node v14.15.0, and it's enforced in the `package.json`, so `npm` had already informed you.
