### ISSUE TITLE
terminal-kit is not working with SSH connection 

### ISSUE THREAD

**Issue by hemendpatel** [cronvel/terminal-kit#212]
I'm trying to push terminal out put over SSH2 to putty.

const tkit = require('terminal-kit');
ssh2 = require('ssh2'),
new ssh2.Server({hostKeys: [hostKeys]}, (client) => {
  var buffer, term;
  term = tkit.createTerminal({
    stdin: client,
    stdout: client
  });
  term.clear();
  term.moveTo(1, 1, "ICU");
  term.width =10
  term.height= 20;
  buffer = tkit.ScreenBufferHD.create({
    dst: term
  });
  buffer.put({
    x: 2,
    y: 2,
  }, "Hello");
  buffer.draw();
}).listen("5151", '0.0.0.0', function() {
  console.log('Listening on port 5151');
});

Error: I'm getting below error:
![image](https://user-images.githubusercontent.com/32077544/186969504-5d6d966c-23a3-45f0-8229-19ff55f21483.png)

does anyone try to use ssh2 connection using terminal-kit?

**Comment by hemendpatel** [comment]
Found the solution!

**Comment by ROTGP** [comment]
> Found the solution!

It would be helpful if instead of telling the world that you found a solution, that you instead share the solution.

**Comment by HemTech** [comment]
Below is the code
![image](https://user-images.githubusercontent.com/49240619/230631365-1aa5d551-9e7d-497d-ad4a-e5adb07a084f.png)
