### ISSUE TITLE
Support gray color

### ISSUE THREAD

**Issue by milesj** [cronvel/terminal-kit#22]
Would be nice to use "gray" instead of "brightBlack". Currently getting `TypeError: Cannot read property 'str' of undefined` when using `term.gray.str('foo')`.

**Comment by cronvel** [comment]
Typically there are 8 colors (black, white, red, yellow, green, cyan, blue, violet/magenta) and their brighter version -> 16 ANSI colors.

I know "brightBlack" sounds weird, but it should at least exist for consistency sake.

Technically, there are 4 black to white colors: black, brightBlack, white, brightWhite. None of them are closed to be gray (#7F7F7F): "brightBlack" is really dark, "white" is already too bright and both are at the same distance from gray. There is **no** ANSI gray color. So it is really hard to choose which one should be aliased as gray.

Anyway, if there is a popular request for that, I will add it.

**Comment by cronvel** [comment]
It looks like other libs/modules are aliasing 'gray' as the 8th color (here 'brightBlack').
So it will be part of the next release.

**Comment by milesj** [comment]
Awesome, glad to hear it!
