### ISSUE TITLE
terminalkit.TextBox is not a constructor

### ISSUE THREAD

**Issue by SinanAkkoyun** [cronvel/terminal-kit#223]
Please help me, on which branch can one use Documents? I tried to install the develop branch via NPM github, but I can't seem to create TextBoxes just like in the example

Thank you very much!

**Comment by SinanAkkoyun** [comment]
My bad, I asusuned because the types didnt include the document model, the main branch also wouldnt, which is incorrect, it does, the typings are just simply not there

**Comment by cronvel** [comment]
Hi @SinanAkkoyun

Sorry, typings are out of date, the maintainer for that is inactive for years.

Also it's recommended to use the releases versions from npm, or if you insist cloning from Github, you should checkout a tag corresponding to the version you want.

**Comment by SinanAkkoyun** [comment]
Thank you very much.

I was wondering about a different thing:
When supplying a pos and width and height, I often supply calculations based on the terminal size for a responsive design that is not limited by percentages (for example when I implement a padding of 2 characters)

For now, it seems that the only way to make this responsive is by subscribing to the resize event and setting every textbox's dimensions there again.

Is there perhaps a way to only supply the width, height and pos with a function that gets called internally every time a resize happens? This way one could eliminate redundancy and one wouldn't have to subscribe to the resize event at all

Much appreciated, thank you for the whole terminal-kit package so much, it really transcended my CLI application to a different level.
