### ISSUE TITLE
How to catch the keypress 

### ISSUE THREAD

**Issue by codekraft-studio** [cronvel/terminal-kit#24]
Hi, first of all, compliments for the module.

I'm using term.on( 'key') to get the user keyboard input, but when I press something like __ARROW_UP__ it produces on screen this: `^[[A` and until I press enter the on('key') callback is not fired.. so, since I need to simulate the cursor moving when the user press arrow keys how can I do?
```
term.grabInput( );
term.on( 'key' , function( key , matches , data ) { 
switch ( key )
    {
        case 'UP' : term.up( 1 ) ; break ;
        case 'DOWN' : term.down( 1 ) ; break ;
        case 'LEFT' : term.left( 1 ) ; break ;
        case 'RIGHT' : term.right( 1 ) ; break ;
        case 'CTRL_C' : process.exit() ; break ;
        default:   
            // Echo anything else
            term.noFormat(
                Buffer.isBuffer( data.code ) ?
                    data.code :
                    String.fromCharCode( data.code )
            ) ;
            break ;
    }
});
```

The example code is from here: [http://blog.soulserv.net](http://blog.soulserv.net/terminal-friendly-application-with-node-js-part-iii-user-inputs/) and (for me) is not working as described.. the arrow keys produces (on screen): `^[[A`, ... and until I press enter the key event is not fired

**Comment by cronvel** [comment]
Can you tell me which OS and terminal you are using?

**Comment by codekraft-studio** [comment]
@cronvel  my fault, since windows was not supported and I was on that OS, I was using a ssh client to connect to a linux machine I own, but 100% the terminal of the ssh client was not supported, when I tried on my laptop that has linux on it, it worked like a charm.

( the terminal I was using is from: [Bitvise SSH](https://www.google.com/search?q=bitvise+sshj&oq=bitvise+sshj&aqs=chrome..69i57j0l5.1389j0j7&sourceid=chrome&ie=UTF-8) if you are interested to add support or to know which terminal was failing )

Many thanks.

**Comment by codekraft-studio** [comment]
@cronvel do you know if is possible with terminal-kit to send the output something different that process stdouput?

I explain, I'm trying to archive something like this (pseudo-code):
```
telnet.createServer(function(client) {
var term = ansi(client, { enabled: true })
term.write('Hello');
})
```
Using the [ansi](https://www.npmjs.com/package/ansi) module is possible to send the output to the telnet client (in this case)

**Comment by cronvel** [comment]
Hello @codekraft-studio 

Have a look at this [constructor](https://github.com/cronvel/terminal-kit/blob/master/doc/global-api.md#ref.createTerminal), it allows you to configure your stdio.

Something similar than this should do the job:

```js
var termkit = require( 'terminal-kit' ) ;

telnet.createServer(function(client) {
    var term = termkit.createTerminal( {
        stdout: client.stdout ,  // just guessing the 'client' structure here
        stdin: client.stdin ,  // just guessing the 'client' structure here
    } ) ;
    term.magenta( 'Hello! in magenta!' ) ;
} ) ;
```

If you need advanced features, your telnet lib should at least support the *raw mode*.

For your windows terminal, can you run some linux text editor with it?
* If you can't, there is nothing we can do.
* If you can, then your windows terminal simply has *bad default* modes, but vanilla Node.js cannot set any TTY mode (beside *raw mode*), you need a native module for that: the solution can be to use the excellent [termios](https://www.npmjs.com/package/termios) module by @Gottox: 

I hesitate to include *termios* in Terminal-kit, but it bothers me to include native module. At the moment, Terminal-kit can be run on any Node.js machine, but if I include native module, it would require a compiler.

**Comment by codekraft-studio** [comment]
@cronvel 

> If you can, then your windows terminal simply has bad default modes, but vanilla Node.js cannot set any TTY mode (beside raw mode), you need a native module for that: the solution can be to use the excellent termios module by @Gottox:

with the terminal provided by Bitvise I can use editors like nano and vim via ssh, eventually I will try to use termios if I really need, but for now i'm just "playing" with the code so I don't want to complicate my life too much.

I didn't see the documentation in deep, sorry I should have checked before!
Later today when I've time I'll try to see if it works like you suggested many thanks!
