### ISSUE TITLE
terminal-kit very upset if TERM is not set

### ISSUE THREAD

**Issue by interfect** [cronvel/terminal-kit#26]
Sometimes (i.e. on Windows), the `TERM` environment might not be set. In `detectTerminal.js`, this [makes `appId` undefined](https://github.com/cronvel/terminal-kit/blob/master/lib/detectTerminal.js#L45), and then [makes `generic` undefined](https://github.com/cronvel/terminal-kit/blob/master/lib/detectTerminal.js#L55) and then [causes a crash when the give-up code tries to convert undefined to lower-case](https://github.com/cronvel/terminal-kit/blob/master/lib/detectTerminal.js#L136).

The solution is to have a fallback string of some sort if none of the environment variables the library is looking for are set. I have no idea if after that the library will work *correctly* on any of these platforms, bit it will at least not explode immediately.

**Comment by cronvel** [comment]
Thanks for reporting it, just fixed it now.
