### ISSUE TITLE
Multi/Split window support

### ISSUE THREAD

**Issue by azfarsiddiqui** [cronvel/terminal-kit#28]
Hi guys, I am pretty new to terminal kit and its continuing to amaze me. I just wanted to find out if there is any way to have multi/split window UI. I am attaching a sample image of what I am looking for. It has a list/table at the left and content area on the right

Thanks guys
![3316428506_a929c7dcbd_o](https://cloud.githubusercontent.com/assets/9972531/26083711/a9489cac-3a1a-11e7-9ed7-9d72933969f2.png)

**Comment by cronvel** [comment]
Hi, 

Splitting in multiple block on top of each others is possible using [`term.scrollingRegion()`](https://github.com/cronvel/terminal-kit/blob/master/doc/low-level.md#moving-the-cursor) but it can't create multiple column like in your screenshot. Terminals doesn't have **native** way to do that. 

**Luckily, Terminal-kit has a feature that abstract away the terminal**, it's called the [**ScreenBuffer**](https://github.com/cronvel/terminal-kit/blob/master/doc/screenbuffer.md#top). However, it totally changes the way to interact with the lib: you should dive in the documentation to learn how it works.

From what I see in your screenshot, you may also need to use the [**TextBuffer**](https://github.com/cronvel/terminal-kit/blob/master/doc/textbuffer.md#top). This is a buffer suitable for things like text-editor, it is less low-level, but it should write to a ScreenBuffer.

So, your example can be coded using 2 ScreenBuffers, one for each panel, and 2 TextBuffers on top of them. The status line does not need anything special at all.

You can see TextBuffer in action in the [Neon editor](https://github.com/cronvel/ne), the project is currently stalled, but it still works for basic usage (and it even supports javascript syntax hilighting).
