### ISSUE TITLE
Do TextBuffers support transparency?

### ISSUE THREAD

**Issue by samizdatco** [cronvel/terminal-kit#33]
I've run into some unexpected differences in behavior between TextBuffers and ScreenBuffers and am wondering if there's a way to get the 'empty' cells in a TextBuffer to be transparent in the same way that empty ScreenBuffer cells are. 

From the docs, my understanding was that calling *.setEmptyCellAttr()* with `charTransparency:true` would mean that empty cells in the TextBuffer wouldn't overwrite the characters in its destination ScreenBuffer. But as you can see in the top screenshot below, the entire 20x3 block of the TextBuffer is overwriting the dots in the background ScreenBuffer.

I had expected results that look more like the bottom screenshot (i.e., without the surrounding black bars). Is this a bug, or am I just misunderstanding how transparency & blending works between TextBuffers and ScreenBuffers?

![terminal-kit-textbuffer-not-blending](https://cloud.githubusercontent.com/assets/469523/26766120/eef432be-4958-11e7-84fe-ab309d7730af.png)
```js
function useTextBuffer(){
  // place a textbuffer in the middle of the destination 
  // screenbuffer and set its empty cells to be 
  // transparent for bg and char
  foreground = termkit.TextBuffer.create({
    dst:background,
    x:10,
    y:8,
    width:20,
    height:3
  })
  foreground.setEmptyCellAttr({
      bgTransparency:true, 
      charTransparency:true
  })

  // the message text should be visible, but the surrounding
  // rows and cols of the TextBuffer should(?) be transparent
  foreground.moveTo(2,1)
  foreground.insert('hello textbuffer')
}

function useScreenBuffer(){
  // place a child screenbuffer in the middle of the
  // parent screenbuffer and draw a similar message
  foreground = termkit.ScreenBuffer.create({
    dst:background,
    x:10,
    y:8,
    width:20,
    height:3
  })

  foreground.put({x:1, y:1}, 'hello screenbuffer')
}

var termkit = require( 'terminal-kit' ),
    term = termkit.terminal,
    foreground, background;

// set up the base ScreenBuffer and add one of our two
// child buffers to it then draw everything to the term
background = termkit.ScreenBuffer.create({
  dst:term,
  x:1, 
  y:1,
  width:40,
  height:20,
  noFill:true
})
background.fill({
  char:'·', 
  attr:{color:'white', bgColor:'brightBlue'}
})

useTextBuffer() // or useScreenBuffer()

term.clear()
foreground.draw({blending:true})
background.draw()
```

**Comment by cronvel** [comment]
@samizdatco That's right, it doesn't support transparency directly.
The purpose of TextBuffer is to manage the text like in a text editor.
It's way more handy than using the ScreenBuffer's low level `.put()` method.
Moreover, the TextBuffer has a virtually infinite size by default, a thing that is not possible with the more concrete ScreenBuffer.
But things like transparency and composition are ScreenBuffer's job.

In fact, the TextBuffer content is just copied as it is (geometry aware) to the ScreenBuffer.
So the transparency flags are written into the ScreenBuffer instead of being applied.

In your example, if you want to achieve what you want, you need one extra ScreenBuffer.
In fact there should always be a ScreenBuffer backer for each TextBuffer, but you can eventully mutualize them if they do not overlap.
In your example the ScreenBuffer used as the backer has overlapping informations (the one *below* the TextBuffer).

**Comment by cronvel** [comment]
@samizdatco This is your modified example:

```javascript
function useTextBuffer(){
  // place a textbuffer in the middle of the destination 
  // screenbuffer and set its empty cells to be 
  // transparent for bg and char
  foreground = termkit.ScreenBuffer.create({
    dst:background,
    x:10,
    y:8,
    width:20,
    height:3
  })
  
  textbuffer = termkit.TextBuffer.create({
    dst:foreground,
    x:0,
    y:0,
    width:20,
    height:3
  })
  textbuffer.setEmptyCellAttr({
      bgTransparency:true, 
      charTransparency:true
  })

  // the message text should be visible, but the surrounding
  // rows and cols of the TextBuffer should(?) be transparent
  textbuffer.moveTo(2,1)
  textbuffer.insert('hello textbuffer', { bgColor: 'blue' } )
  
  textbuffer.draw()
}

function useScreenBuffer(){
  // place a child screenbuffer in the middle of the
  // parent screenbuffer and draw a similar message
  foreground = termkit.ScreenBuffer.create({
    dst:background,
    x:10,
    y:8,
    width:20,
    height:3
  })

  foreground.put({x:1, y:1}, 'hello screenbuffer')
}

var termkit = require( 'terminal-kit' ),
    term = termkit.terminal,
    textbuffer, foreground, background;

// set up the base ScreenBuffer and add one of our two
// child buffers to it then draw everything to the term
background = termkit.ScreenBuffer.create({
  dst:term,
  x:1, 
  y:1,
  width:40,
  height:20,
  noFill:true
})
background.fill({
  char:'·', 
  attr:{color:'white', bgColor:'brightBlue'}
})

useTextBuffer() // or useScreenBuffer()

term.clear()
foreground.draw({blending:true})
background.draw()
```

Note how there are one more buffer in the `.useTextBuffer()` method.
Also note that you should give the attr when inserting or it will default to the *emptyCellAttr*.

**Comment by samizdatco** [comment]
Thanks for explaining. That clears things up considerably.
