### ISSUE TITLE
Autocomplete not working?

### ISSUE THREAD

**Issue by eduardoportilho** [cronvel/terminal-kit#34]
I've copied and run the documentation example that features history and auto-completion, but the auto-complete is not working for me. Can you help me to understand why? 

(I'm using node v6.8.1, terminal-kit@1.10.2, iTerm and Fish shell).

![jun-14-2017 18-08-04](https://user-images.githubusercontent.com/895865/27142795-844617b2-512c-11e7-975c-38dedc081398.gif)

**Comment by cronvel** [comment]
@eduardoportilho Hmm... really strange... 
Can you run ./sample/key-test.js and hit the *TAB* key, and report me what is detected?

**Comment by eduardoportilho** [comment]
Aha, I didn't press the `tab` key... 😞😞😞
Sorry about that.
