### ISSUE TITLE
How to keep a progress bar at the bottom of the terminal?

### ISSUE THREAD

**Issue by vwalsh** [cronvel/terminal-kit#36]
Hello,

I've been trying to figure out how to create output similar to how Ubuntu's "apt update" and "apt upgrade" commands work - they show a bunch of output of lines of data, and appended to the bottom of the entire terminal is progress bar.

Currently I'm able to create the progress bar and output items all using terminal-kit, except when my progress bar is 'done' it get's overwritten by the next text output. in steps this looks like this in my code:

1. start progress bar
2. update progress bar
3. progress bar finishes
4. output text of further tasks

Sample Output:
!B       audio/Thanks-v1.wav=========>] done                               
!B       audio/outro-v2.wav
!B       audio/Outro-V1.wav
!B       assets/timecode-2.5min.mp4
!B       assets/60-opacity.png

Desired Output:
!B       audio/Thanks-v1.wav                           
!B       audio/outro-v2.wav
!B       audio/Outro-V1.wav
!B       assets/timecode-2.5min.mp4
!B       assets/60-opacity.png
( more text output here )
Progress: 100%[======================>] done   

I've tried the "moveTo" before writing the next text after a progress bar and I'm not seeing any better results. The progress bar always get's overwritten by the next text output.

My environment is:
Mac OSX El Capitan (10.11.6)
NodeJS 6.5.0
Terminal Kit 1.10.2.

I've been able to build a pretty nice UI in my first usage of this toolkit and it worked really well, so perhaps I've done something wrong. Thanks again for such a great tool!

**Comment by cronvel** [comment]
@vwalsh Yes, the progress bar used to be locked in-place, but I just published v1.11.0 where the option 'inline' (when set to true) turn on the behavior you need.

**Comment by cronvel** [comment]
@vwalsh Does it works for you? So we can close this issue...

**Comment by vwalsh** [comment]
This does seem to have the desired effect, i'm still tinkering with my code to get it to display the way I'd like. I seem to still overwrite the progress bar when it finishes and more text is output to the console. I'll verify what/why that is before I ask for more help.

Thanks again!
