### ISSUE TITLE
Nested ScreenBuffer

### ISSUE THREAD

**Issue by VertigoRay** [cronvel/terminal-kit#39]
I'm having trouble getting nested `ScreenBuffer`s to work in my `account()` function. I'm sure I'm just going about it wrong, but could use some direction. I'm simply not finding an example to reference.

The end goal is to have a section (the grey rectangle) that has several pieces of information in different areas that are updated regularly; as shown by the green rectangles. Unfortunately, I'm not able to get those nested `ScreenBuffer`s to show content.

![image](https://user-images.githubusercontent.com/792482/28237423-c8b2a358-6904-11e7-9e44-91ffdcdacde7.png)

*Forgive my Photoshop skills, please. Also, the green rectangles will end up not being colored; they'll be grey as well.*

Additionally, I'm not sure if I have to fill the `ScreenBuffer` with spaces to color the background gray. Is there a better way?

# Code

```js
const os = require('os');
const pjson = require('../package.json');
const prettyBytes = require('pretty-bytes');
const settings = require('config');
const sprintf = require('sprintf-js').sprintf;
const term = require('terminal-kit').terminal;
const tkit = require('terminal-kit');



function account () {
	let info = sprintf('CPU Cores: %d   |   Free Memory: %s', os.cpus().length, os.freemem());
	let c_justify = parseInt((term.width / 2) - (info.length / 2)) + 1;
	let fill = new Array(term.width).join(' ');
	

	let b_line1 = tkit.ScreenBuffer.create({
		dst: b_account,
		X: 1,
		y: 3,
		width: term.width-2,
		height: 1,
		// blending: true,
		// noFill: true,
	});

	let b_line2 = tkit.ScreenBuffer.create({
		dst: b_account,
		X: 2,
		y: 3,
		width: term.width-2,
		height: 1,
		// blending: true,
		// noFill: true,
	});

	let b_line3 = tkit.ScreenBuffer.create({
		dst: b_account,
		X: 3,
		y: 3,
		width: term.width-2,
		height: 1,
		// blending: true,
		// noFill: true,
	});


	let options = {
		x: 1,
		y: 0,
		wrap: false,
		attr: {
			color: 'black',
			bgColor: 'gray',
		},
	};

	// b_account.put(options, fill);
	b_line1.put(options, fill);
	b_line1.draw();
	b_line2.put(options, fill);
	b_line2.draw();
	b_line3.put(options, fill);
	b_line3.draw();

	options.x = c_justify
	b_account.put(options, info);
	b_account.draw();
}



function footer (bytesReceived) {
	let info = sprintf('CPU Cores: %d   |   Free Memory: %s   |   WebSocket Bytes Received: %d', os.cpus().length, prettyBytes(os.freemem()), parseInt(bytesReceived));
	let c_justify = parseInt((term.width / 2) - (info.length / 2)) + 1;
	let fill = new Array(term.width + 1).join(' ');
	
	let options = {
		x: 0,
		y: 0,
		wrap: false,
		attr: {
			color: 'black',
			bgColor: 'white',
		},
	};

	b_footer.put(options, fill);

	options.x = c_justify
	b_footer.put(options, info);
	b_footer.draw();
}



function header () {
	let options = {
		x: 1,
		y: 0,
		wrap: false,
		attr: {
			color: 'brightYellow',
			bgColor: 'cyan',
			bgTransparency: true,
		},
	};

	b_header.put(options, 'Testing Terminal Kit v%s', pjson.version);

	let node_env = sprintf('W:%d H:%d   |   NODE_ENV: %s', term.width, term.height, process.env.NODE_ENV);
	let r_justify = term.width - (node_env.length + 1);

	options.x = r_justify
	b_header.put(options, node_env);

	b_header.draw();
}


var b_header = undefined;
var b_account = undefined;
var b_footer = undefined;
function load_layout() {
	b_header = tkit.ScreenBuffer.create({
		dst: term,
		X: 1,
		y: 1,
		width: term.width,
		height: 1,
	});


	b_account = tkit.ScreenBuffer.create({
		dst: term,
		X: 1,
		y: 3,
		width: term.width-2,
		height: 3,
		// blending: true,
		// noFill: true,
	});


       // Will add additional sections later.


	b_footer = tkit.ScreenBuffer.create({
		dst: term,
		X: 1,
		y: term.height,
		width: term.width,
		height: 1,
		// blending: true,
		// noFill: true,
	});
}



term.windowTitle('Testing Terminal Kit');

// Clear Screen
term.clear();
term.moveTo(1, 1).bgCyan.brightYellow.eraseLine();
term.eraseDisplayBelow();

// Events
term.on('resize', (width, height) => {
	// console.log('TERM RESIZED:', width, height);
	load_layout();
})


load_layout();
header();
account();
footer();



module.exports = function (input, done) {
	header();
	footer(input.bytesReceived);
}
```

**Comment by cronvel** [comment]
Hi @VertigoRay 

Few comments:
- screenBuffer instances got a [`.fill()`](https://github.com/cronvel/terminal-kit/blob/master/doc/screenbuffer.md#ref.ScreenBuffer.fill) method, no need to use `.put()` with an array to init them
- terminal instances **and** `screenBuffer.put()` already got printf-like behavior, you don't need an *sprintf* module at all.
  E.g.: `screenBuffer.put( options, 'CPU Cores: %d   |   Free Memory: %s' , os.cpus().length , os.freemem())`
- screenBuffer are already init with space characters
- your `account()` function actually draws the same things in all screenBuffer: the *gray* background color, that's why you can't see anything, I'm not sure what you are trying to do there

**Comment by VertigoRay** [comment]
I'm trying to make something like a `<table>` (html). It won't necessarily have a header row, but I can fill in the grid with data. Some of the cells will be labels, others will be data. That account area will show account information. I'll make several other sections to show status of others, but they're all generally shaped the same.

The end goal for that account section is to have something like this:

| Account |           |                            |            |                 | %AccountID% |
| --------- | ------ | ------------------ | ------- | ---------- | ---------------- |
| USD:      |  Avail: | %AvailBalance% | Totals: | Sell Now: | %SellNow%     |
|               |  Total: | %TotalBalance% |            | Wait Fill:  | %WaitFill%       |

Obviously, the empty cells, don't need to be cells ... I'm just trying to structure it well so you can get a visual. It doesn't even have to be cells; that's just the way my brain is organizing it right now.

Ideally, I can just call the `account()` function, passing a `data` parameter (doesn't exist yet), and it'll fill in the `%Variables%`.

The interface will just show data output for now. I don't plan to have any inputs or menus or anything. I have a config file for that. Maybe someday, I can add that into the interface, but it's definitely not going to be part of v1.  

I remember trying to `fill()` and getting weird artifacts. I'll look at the documentation again to make sure I was doing it correctly.

I already built this in electron, but now I want to run it on a headless server. I thought having the output display in a similar fashion would work well, and I could just leave it running in screen. Anyway, I think that explains what I'm trying to do a little better. Thoughts?

**Comment by VertigoRay** [comment]
I definitely wasn't doing the `fill()` correctly. I have that working now.

**Comment by VertigoRay** [comment]
Maybe I'm just doing the nested `ScreenBuffer`s wrong, but it's still not working:

The label, "Account", it's showing up in the top left of the box:
![image](https://user-images.githubusercontent.com/792482/28244943-7b4b0d74-69bf-11e7-9044-7068344cd5ec.png)

I did confirm that I can fill in coordinates and just redraw the main account box. Should I just do that, or do you happen to have a better way?

**Comment by cronvel** [comment]
Depending on the level of complexity of your application, it may be overkill to use nested screenBuffers, and might even be overkill to use screenBuffers at all.

Are those cells static? dynamic? contains user input? Is the app *redraw-intensive*? 

- For static cells or if the redraw rate is low, without user interaction, I would avoid screenBuffers, since they are a bit too low-level
- For dynamic cells with intensive redraw, I could go either way, but wouldn't nest
- If there are a lot of user input widget, I would use the document model, but unfortunately this is still an undocumented alpha feature. You can have a look of the document model capabilities in sample code, into the `sample/document/` folder

Nested ScreenBuffer are trivial to understand:
- first *draw* the nested screenBuffers to the master screenBuffer
- then *draw* the master screenBuffer to the terminal
- nested screenBuffer coordinates are relative to the master screenBuffer

**Comment by VertigoRay** [comment]
Seems to be going in a favorable direction now. Thanks so much for your guidance.

![image](https://user-images.githubusercontent.com/792482/28252099-30d4a262-6a52-11e7-9534-bd2d526316e1.png)
