### ISSUE TITLE
What is the fastest way to write the full screen?

### ISSUE THREAD

**Issue by ashnur** [cronvel/terminal-kit#4]
Suppose I have some `width*height*color` array. Is there another way to draw this data to the screen than to call for each element `term.colorRgb(r,g,b)(brush)` ?

**Comment by cronvel** [comment]
What you want to achieve exactly?

There is an undocumented feature called ScreenBuffer in Terminal-kit.
Basically, it's like sprite for the terminal.

There is a ScreenBuffer demo shipped with the lib: demo/spaceship.js.
It's well optimized, as you can see: it only writes the part that changed.

Tell me if this is what you need.

I will document ScreenBuffer when I will be 100% sure of its API, its name, and so on.

**Comment by ashnur** [comment]
I am mostly just trying out things. My current focus is on trying to paint as much frames as possible, I've seen things like movie players with ascii symbols. I don't actually want that, I think at first I will do some kind of a silly game. 
This ScreenBuffer sounds exactly what I need, I will try it out and report back. Thanks. (The changing api is not a problem because I am just experimenting right now :) )

**Comment by cronvel** [comment]
If you want to do a little game, have a look at [Leeted](https://github.com/cronvel/leeted) (leet editor), it is a little tool (still in alpha) that can produce ASCII sprite with colors and all. It can save them and terminal-kit can load them. I don't have time to improve Leeted right now, but it should be good enough for a little game!

You should definitively have a look at the code of the spaceship demo, it was done using ScreenBuffer and Leeted ;)

**Comment by cronvel** [comment]
I have updated the README.md of LeetEd, the keys and their actions are now listed ;)
