### ISSUE TITLE
How to return the string using .str()?

### ISSUE THREAD

**Issue by atombrenner** [cronvel/terminal-kit#42]
Maybe I misunderstand the documentation, but shouldn't
`term.blue('BLUE').str()' return a string with escape codes for blue? It always print the string in blue to the terminal.

**Comment by cronvel** [comment]
@atombrenner In your example, `term.blue('BLUE')` write 'BLUE' in blue and return `term`, **then** `.str()` return an empty string.

* If you want the escape code for blue and nothing else, then you must chain this way: `term.str.blue()` or `term.blue.str()`.
* If you want a string containing the escape code for blue, the text 'BLUE' **and** the style reset escape sequence, then you must chain this way: `term.str.blue( 'BLUE' )` or `term.blue.str( 'BLUE' )`.

I usually prefer *term.str.something()* over *term.something.str()*, if I was not planning using terminal-kit to output things to the console, I would require it this way:
```
var termString = require( 'terminal-kit' ).terminal.str ;
```

**Comment by atombrenner** [comment]
Ahhh, now I got it :-) Thanks for the explanation!
