### ISSUE TITLE
Stop scrollback in fullscreen()

### ISSUE THREAD

**Issue by calebjclark** [cronvel/terminal-kit#43]
Is there a way to stop the user from scrolling up above the fullscreen window while fullscreen() is enabled? Blessed does this, but I haven't been able to make it work with terminal-kit.

**Comment by cronvel** [comment]
@calebjclark I don't *exactly* what you mean, but here are some ideas:

* `term.clear()` erase the screen and move the cursor to the upper-left corner
* `term.eraseScrollback()` erase the saved line
* using `term.alternateScreenBuffer()` or [.fullscreen()](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.fullscreen) switch to an alternate screenbuffer that is the exact size of your terminal, no more line are saved into the history

A combination of some of the three should do the job.

**Comment by cronvel** [comment]
@calebjclark Any feedback on that issue? Is it solved?
