### ISSUE TITLE
Hmm how do you show Done in the progress bar

### ISSUE THREAD

**Issue by davidgatti** [cronvel/terminal-kit#44]
Maybe I'm blind, but some who the example code shows Done when the progress bar reaches 100%. But for some reason when I use the progress bar I don't get that? What triggers this action?

**Comment by cronvel** [comment]
@davidgatti If you run the script located in sample/progress-bar-doc1.js, do you get it?

It should works, however I need more information to figure out what happened (your terminal and your code).

**Comment by davidgatti** [comment]
OK, sure, your code (2nd example) have a nice Done in bright white in the end. Shown in the screenshot bellow:

![screen shot 2017-08-24 at 4 44 59 pm](https://user-images.githubusercontent.com/411114/29672118-9fc96d8a-88eb-11e7-9eb4-1cbba17fdb74.png)

I of course modified your example to fit my needs, and now I wonder... did I removed a crucial part? Because I can't see or figure out what is missing, thus my curiosity what triggers this `Done`. 

The project that I'm working on is public so you can check it out here.

- [Line 5](https://github.com/sequr/sequr-import-avatar/blob/staging/sequr/upload.js#L5): I set the variable
- [Line 179](https://github.com/sequr/sequr-import-avatar/blob/staging/sequr/upload.js#L179): I prepare the progress bar with the right size, after I know the size :)
- [Line 237](https://github.com/sequr/sequr-import-avatar/blob/staging/sequr/upload.js#L237): I start the progress bar
- [Line 306](https://github.com/sequr/sequr-import-avatar/blob/staging/sequr/upload.js#L306): I tell the progress bar when it is done with the current element.

So my thinking here, is that after the `items` count goes to 0 you show the Done. But it seams that I must do something more to make it happen. This is of course not the end of the world, but it be nice to have it if possible.

**Comment by cronvel** [comment]
@davidgatti Hmm, that's strange, I can't see why it wouldn't works... Is there any `process.exit()` somewhere that can quit *before* it actually print 'Done'?

**Comment by cronvel** [comment]
@davidgatti Ah ok, I found it: you haven't turned on the *eta* option. In fact `done` is written on the *eta* area of the progressBar, and since you turned it off, it cannot be displayed.

**Comment by davidgatti** [comment]
O thank you! And actually both suggestions need to be done:

- add eta
- and add a small delay.

Then it all works :) 

I'm glad you liked the style :) I'm doing my best to make it nicer for other to follow :)
