### ISSUE TITLE
How to select a folder ?

### ISSUE THREAD

**Issue by jy95** [cronvel/terminal-kit#49]
Hello,

Thanks for this great lib.
Is it possible to select a folder with a function like [.fileInput( [options] , callback )](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#fileinput-options--callback-) ?

Thanks

**Comment by cronvel** [comment]
@jy95 Hello, and thanks for the praise!

If you mean *force the selection of an existing folder*, the response is no. 
At the moment, `.fileInput()` is like a regular `.inputField()`, with a file/folder auto-completion.
It does not enforce anything.
