### ISSUE TITLE
Efficient way to erase characters in a specific area?

### ISSUE THREAD

**Issue by laurent22** [cronvel/terminal-kit#51]
I'm not sure if this already part of the API and I missed it, but is there any way to erase a specific part of the terminal *without* moving around other characters?

eg. for example I have this:

	0123
	5678
	9012

And want to have this (erase the two characters in the middle):

	0123
	5  8
	9012

I found a way by doing this:

	term.moveTo(2,2);
	term.delete(2);
	term.insert(2);

But that seems a bit inefficient. Is there a better way?

**Comment by cronvel** [comment]
Not really, except if you want to erase from your actual cursor to the end of line (`eraseLineAfter()`).

More efficient: `term.moveTo( 2 , 2 , '  ' ) ;` or `term.moveTo( 2 , 2 , ' '.repeat( 2 ) ) ;`

Also it could be interesting to have a higher-level function for erasing region, but it would definitively do something similar behind the scene.

**Comment by laurent22** [comment]
Great, thanks I missed that it was possible to do `moveTo(x, y, chars)`.

A function like `erase(x, y, width, height)` would be quite convienent. I can provide a pull request if you're interested?

Also another question, the `insert(x)` function actually inserts space characters, is that right? Or does it take the character it's inserting from somewhere else? (It wasn't clear from the documentation)

Yes I had a look at ScreenBuffer but since what I want to do is quite custom (multiple scrollable lists and a text input below), I thought I'd try first with something lower level to have more flexibility. It's possible I'm reinventing the wheel though!

**Comment by cronvel** [comment]
@laurent22 Hi, as you can see, I have added the `.eraseArea( x , y , [width] , [height] )` method that does exactly what you want.

For the `.insert()` method, it directly map to a terminal capability. So I cannot tell you if it actually adds *space* characters, or if a terminal has an internal *empty cell state*. However since empty areas act as spaces when we copy/paste them, that's not really important.

**Comment by laurent22** [comment]
Brilliant, thanks a lot for the `eraseArea` function!
