### ISSUE TITLE
"resize" event not working?

### ISSUE THREAD

**Issue by laurent22** [cronvel/terminal-kit#54]
I'm trying to get the `resize` event to work, or simply to get the new terminal height whenever it's resized, but it's not working so far.

I've narrowed it down to this simple script:

````
var term = require( 'terminal-kit' ).terminal ;

setInterval(function() {
	console.info(term.height);
}, 1000);

term.on('resize', function(width, height) {
	console.info('Resize: ' + width + ', ' + height);
});
````

This will continuously print the same size, even as I resize the terminal, and the "resize" event is never fired.

If I Ctrl+C the script and start it again, it will then pick up the new terminal size, so it's getting it right but it just never updates once the script starts.

I've tried in ConEmu and the default Windows terminal, both under WSL and DOS but none of these are working. Any idea what could be the issue?

**Comment by cronvel** [comment]
@laurent22 Can you test it with those events:
- process.stdout.on( 'resize' , callback )
- process.on( 'SIGWINCH' , callback )

Terminal-kit use Node for that, and I don't know if Windows reports terminal resizing at all.

**Comment by cronvel** [comment]
Apparently, this is a [known issues in the node.js repository](https://github.com/nodejs/node/issues/13197) .

**Comment by laurent22** [comment]
> process.on( 'SIGWINCH' , callback )

Seems that's the key. If I add an event listener for this, then the rest of it suddenly works. i.e. this doesn't work:

````
var term = require( 'terminal-kit' ).terminal ;

console.info('process.stdout.isTTY = ' + process.stdout.isTTY);

setInterval(function() {
	console.info(term.height);
}, 1000);

term.on('resize', function(width, height) {
	console.info('Resize: ' + width + ', ' + height);
});

process.stdout.on('resize', function() {
	console.info('Resize (process.stdout)');
});
````

However if I add this at the bottom:

````
process.on('SIGWINCH', function() {
	console.info('Resize (SIGWINCH)');
});
````

Then this event handler *and* the two previous ones also start working, so it seems adding this trigger something that makes terminal-kit (and node) detect resize events correctly.

`process.stdout.isTTY` is `true` on my machine.

Maybe the solution would be to enable the `SIGWINCH` method if the operating system is Windows, regardless of `isTTY`?

**Comment by cronvel** [comment]
@laurent22 Wow, what an incredibly awkward behavior... -_-'
Was that tested inside WSL?

**Comment by laurent22** [comment]
Yes that was inside WSL, from ConEmu (in tmux if it makes a difference).

**Comment by cronvel** [comment]
@laurent22 Does this fix this issue?

**Comment by laurent22** [comment]
Unfortunately it still shows the same problem. I've tried running the file all-event-test.js and it didn't detect the resize event. However again if I add this line at the bottom: `process.on('SIGWINCH', function() {});` then the call `term.on( 'resize'...` magically starts working.

**Comment by cronvel** [comment]
@laurent22 Argh... what is the value of `process.platform`?

**Comment by laurent22** [comment]
Oh right I see you have a check on process.platform, but on Windows WSL it actually returns "linux". If needed there's a package here that can detect WSL: https://github.com/ianmitchell/is-windows-bash

**Comment by refack** [comment]
Can anyone check if this reproduces with `node@8.7.0`?

**Comment by cronvel** [comment]
@laurent22 ?

**Comment by laurent22** [comment]
@refack, yes it's still happening in node 8.7.0. This doesn't work;

````js
setInterval(function() {}, 1000);

process.stdout.on('resize', function() {
	// Never fires
	console.info('Resize (process.stdout)');
});
````

But with the empty `process.on('SIGWINCH', function() {});` at the bottom it does:

````js
setInterval(function() {}, 1000);

process.stdout.on('resize', function() {
	console.info('Resize (process.stdout)'); // It works
});

process.on('SIGWINCH', function() {});
````

**Comment by refack** [comment]
@laurent22 thanks! 
Now waiting for https://github.com/nodejs/node/pull/16225

**Comment by laurent22** [comment]
Brilliant, thanks for the update!

**Comment by cronvel** [comment]
Great!
That reminds me that I definitively need a Windows maintainer...

**Comment by laurent22** [comment]
I can help with that if needed. I'm using Terminal Kit quite a lot in a note-taking app I'm working on at the moment (it's [here](https://github.com/laurent22/joplin/tree/tkwidgets) but not officially released yet) and I'm only using Windows. For the most part I didn't have any issue actually other than the `resize` issue, which is more a Node regression.

**Comment by refack** [comment]
If you need Windows specific review, feel free to ping me as well.

**Comment by cronvel** [comment]
@laurent22 @refack Thanks a lot, it will be really useful. I don't have Windows anymore and I never used it for dev, so I terribly lack experience. And there are many specific environments like Cygwin and WSL, or various terminals more or less compliant (putty, console2, etc).
I realize that there are more Node.js developers working on this platform than I could imagine, and I would be happy if they could fully enjoy the lib ;)
