### ISSUE TITLE
Position at specific location in inputField?

### ISSUE THREAD

**Issue by laurent22** [cronvel/terminal-kit#56]
I was wondering is it currently possible to programmatically move the cursor in an inputField? The use case I have in mind is that I display an inputField and pre-populate with eg `mkdir ""` and I move the cursor automatically between the quotes so that the user can start typing from there directly.

I know there's already something to start with a default value but I couldn't find how to set the cursor. Can this currently be done?

**Comment by cronvel** [comment]
@laurent22 It was not possible, but I added that feature just now, see [the doc](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.inputField).

Either you pass the `cursorPosition` option, or you use the method `.setCursorPosition()` of the object returned by `.inputField()`. Both support negative values: it starts from the end of input.

**Comment by laurent22** [comment]
That's perfect, it works great. Thanks a lot!
