### ISSUE TITLE
restoreCursor not working when current line is at bottom of terminal?

### ISSUE THREAD

**Issue by ctataryn** [cronvel/terminal-kit#59]
I am trying to use a `singleColumnMenu` to display some options. The idea here is when the user selects an item, the app will:

1. Clear the `singleColumnMenu`
2. Replace it with a `.inputField`
3. Gather the input
4. Redisplay the `singleColumnMenu` where it was before

I tried some preliminary code to see if I could accomplish steps 1-2, but `restoreCursor()` is acting in a nondeterministic fashion.  I'm on OSX in Terminal.app.

If I cmd-K my terminal to clear the screen, my app works perfectly. In fact I can execute the app a few times and it still works perfectly.  However, when my terminal's prompt get down near the bottom of my terminal screen and I execute my program, the menu is not erased and the input is placed after the menu items.  If I cmd-K and run again, everything works fine again.  

I've attached a gif that shows what's happening.

![Curson Restor Problem](https://user-images.githubusercontent.com/435719/32807866-f60dff20-c956-11e7-8102-79d5f8f12d1a.gif)

Here is the code:

```javascript
var term = require( 'terminal-kit' ).terminal ;

var items = [
  'Option 1.' ,
  'Option 2.' ,
  'Option 3.'
] ;

term.saveCursor();
start();

function start() {
  //display the menu
  term.singleColumnMenu( items , ( error , response ) => {
    //restore the cursor to where it was before the menu was displayed
    term.restoreCursor();
    //console.log(`origX=${origX}, origY=${origY}`);
    //term.moveTo(origX, origY);
    term.eraseDisplayBelow();
    //dsiplay the input field where the menu once was
    term(' Enter some text: ');
    term
      .inputField(function( error, input ) {
        term.restoreCursor();
        term.eraseDisplayBelow();
        term.singleColumnMenu( items, (error, response) => { process.exit(); } );
      });
  } ) ;
}

```

**Comment by cronvel** [comment]
@ctataryn Hi, `.saveCursor()/.restoreCursor()` **are** deterministic, however you are suggesting it works on a coordinate system based upon the text flow, while in reality it works with the terminal coordinate system.

Let me explain what happened:
- the cursor is at the bottom of the screen, you save its position
- some text forces a scrolling of the terminal's content
- you restore the saved cursor position, but it has scrolled and the cursor doesn't care about it: it is **indeed** restored at the bottom of the screen

But you want to move the cursor at the beginning of the single column menu. Sadly there is no easy way to do it, since terminals don't track scrolling. They do not emit some magical *terminal scrolling* event that Terminal-kit would receive, so you are basically on your own because you alone know what your app is doing.

There are a lot of workaround for that, for example:
- don't use `.saveCursor()/.restoreCursor()`, instead move the cursor up using the appropriate number of line (since you know how many options are sent to `.singleColumnMenu()`.
- before using `.saveCursor()/.restoreCursor()`, output some `\n` then call `term.up(n)` with *n* matching the number newline characters: this way you prepare an area big enough to receive your `.singleColumnMenu()`

**Comment by cronvel** [comment]
A better approach:
```js
var term = require( 'terminal-kit' ).terminal ;

var items = [
    'Option 1.' ,
    'Option 2.' ,
    'Option 3.'
] ;

start();

function start() {
    //display the menu
    var menu , inputField ;
    
    menu = term.singleColumnMenu( items , ( error , response ) => {
        var position = menu.getPosition() ;
        term.moveTo( position.x , position.y ) ;
        term.eraseDisplayBelow();
        term(' Enter some text: ');
        
        inputField = term.inputField( ( error, input ) => {
            var position = inputField.getPosition() ;
            // set x to 1 because the .inputField() start after ' Enter some text: '
            // set y to position.y - 1 because .singleColumnMenu() always add a newline
            term.moveTo( 1 , position.y - 1 ) ;
            term.eraseLineAfter();  // erase current line after the cursor
            term.eraseDisplayBelow();  // erase below
            term.singleColumnMenu( items, ( error, response ) => { process.exit(); } );
        } ) ;
    } ) ;
}
```
The trick is to use `.getPosition()` on the returned menu/inputField controller.

**Comment by ctataryn** [comment]
One thing I noticed is that after you run it a few times and get to the bottom of the terminal, the `Enter some text: ` prompt doesn't get erased and the menu redisplays several lines under the prompt.

![end of terminal problem](https://user-images.githubusercontent.com/435719/32873786-a13ccdf2-ca53-11e7-98ff-16c263fdc405.png)


So I think the problem still persists?  But thank you for such a thorough answer, the explanation and code was very helpful.

**Comment by ctataryn** [comment]
Oh, never mind. I had an extra line of code I shouldn't have had on my side.

Just a question...
What I thought I could do instead was, within the `menu`'s callback, call `menu.hide()` and then in the `inputField`'s callback I could call `menu.show()`. That visually works great for me!  However, the menu no longer responds to keyboard navigation. I believe it's because the menu has a selected item already, is there a way to tell it to reset?

**Comment by cronvel** [comment]
@ctataryn Ok, I didn't understood that your intend was to use twice the same menu.

The default behavior is that once something is selected, the callback is fired and the menu stop doing anything.

To prevent this, you can use the [*continueOnSubmit* options](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.singleColumnMenu):
> * continueOnSubmit boolean if true, the submit action does not end the menu, the callback argument is ignored. The 'submit' event should be listened instead.

So... use a combination of `menu.on( 'submit' , () => { ... } )`, `menu.hide()`, `menu.pause()` (stop doing things on key/mouse event), `menu.show()`, `menu.resume()` (start listening key/mouse again). You can `menu.abort()` it when you're done.

**Comment by ctataryn** [comment]
Very good! Thank you, you’ve done such a great job on documentation that I should have been able to piece that together myself! Thanks for your patience. 🙏🏻

________________________________

**Comment by cronvel** [comment]
@ctataryn You're welcome! ;)

**Comment by ctataryn** [comment]
@cronvel even with `{ continueOnSubmit: true }` the menu seems to hang when I execute the following in the `inputField`'s callback:

```javascript
    menu.show();
    menu.resume();
```

The menu item selected still has that "in the process of being submitted" sort of look after it is resumed:

![after submission, ](https://user-images.githubusercontent.com/435719/32917027-8098f78e-cae3-11e7-999b-581c36564046.png)


On a side note, is it possible to have the menu redraw it's items on demand? Within the `inputField` callback I want to manipulate the menu's items and have it reflected in the menu.

My `displayMenu()` function looks like this now, btw:

function displayMenu(items) {
  menu = term.singleColumnMenu( items , { continueOnSubmit: true });
  menu.on('submit', ( response ) => {
    var position = menu.getPosition();
    menu.pause();
    menu.hide();
    switch (response.selectedIndex) {
      case Menu.MONGO.idx:  { displayInput(' Enter a Mongo Query: ', 'MONGO'); break; }
      case Menu.EXIT.idx:   { menu.abort(); process.exit(); }
      default: displayInput(' Enter some text: ');
    }
  });
}

**Comment by cronvel** [comment]
@ctataryn Well it is not that flexible! There is no way to change the menu items at the moment... To redraw, you can call `menu.redraw()`. If you want to change the menu items, you need to revert back to your previous algorithm, where you create a new menu anytime you're done with your input field.

**Comment by ctataryn** [comment]
Ok, I may have to do that anyway given the behaviour I’m experiencing with the menu not responding to keyboard input after an item is selected even with `continueOnSubmit` being set and using `.resume()`


________________________________

**Comment by cronvel** [comment]
@ctataryn Maybe it's not well documented here, but when using `continueOnSubmit`, most keys stop doing anything unless the user *cancel* its choice with the *backspace* or *delete* key (key bindings are configurable).

To be honest, the menu was coded with *one menu call per user input* in mind.

**Comment by ctataryn** [comment]
Fair enough, I’ll change my approach back to the original way. Again, thank you for your attentive help.

________________________________
