### ISSUE TITLE
Funny cursor positions depending on invocation of `singleColumnMenu`

### ISSUE THREAD

**Issue by ctataryn** [cronvel/terminal-kit#60]
If I invoke a `singleColumnMenu` like so:

```javascript
function displayMenu(items) {
  menu = term.singleColumnMenu( items, ( error, response ) => {
    eraseMenu();
    switch (response.selectedIndex) {
      case Menu.MONGO.idx:  { 
         term(' Enter a Mongo Query: ');
         inputField = term.inputField(function( error, input ) { ... });
         break; 
      }
      case Menu.EXIT.idx:   { menu.abort(); process.exit(); }
      default: displayInput(' Enter some text: ');
    }
  });
}
```

Everything works great like so:

![Working...](http://g.recordit.co/SXVOtXAyCr.gif)

However, if I move that `singleColumnMenu` callback into an `.on('submit', ..._` block, the following behaviour happens (i.e. `inputField` is moved to the bottom of the now-erased menu):

![Not working](http://g.recordit.co/EHtcy9V4Vp.gif)

Full code can be found here:

https://gist.github.com/ctataryn/58ed333e4d810073e7b766425889b325

**Comment by cronvel** [comment]
* The *submit* event is invoked immediately. The *submit* event is designed to work with the *continueOnSubmit* option, i.e. when the menu is kept alive after submitting.
* The callback is not designed to work with *continueOnSubmit*, it is triggered after submitting and after cleaning up the menu: once everything is done.

In your case, use the callback. ;)

**Comment by ctataryn** [comment]
Thanks, I saw that  doc but I couldn’t put 2+2 together as to why my cursor position wasn’t working, but it makes sense now. The cursor is already set to be after the menu since it’s all submitted and cleaned up by that point 👍🏻

________________________________
