### ISSUE TITLE
singleColumnMenu works bad with long arrays

### ISSUE THREAD

**Issue by zlydenko** [cronvel/terminal-kit#64]
It displays only a few last items in array 😢

**Comment by cronvel** [comment]
You mean when your terminal has less line than the number of menu items?

**Comment by cronvel** [comment]
@zlydenko any details?

**Comment by zlydenko** [comment]
@cronvel first of all its clear console window and then display only a few last lines of array (i have search results in array ~60-70 lines and he displayed only 10 or less). Im using cmder console for Windows, OS: win10.

**Comment by shanehsu** [comment]
I believe the OP expects the menu to scroll if the number of items exceeds the terminal height.

**Comment by cronvel** [comment]
It looks like it's the same than #91 so I'm closing this one.
