### ISSUE TITLE
Using `.length` on .singleColumnMenu's menuItems doesn't work well with ANSI escape sequences

### ISSUE THREAD

**Issue by domq** [cronvel/terminal-kit#68]
Should either
  * let user provide custom length,
  * or use [strip-ansi](https://www.npmjs.com/package/strip-ansi)

**Comment by cronvel** [comment]
Hi @domq,
Thanks for your PR, but there are other things to be aware of, like full-width chars.
I will try to fix that later in the next week if I have time.

**Comment by ponsfrilus** [comment]
Hi @domq and @cronvel,
   I've just written [a test file](https://gist.github.com/ponsfrilus/309c4e44e9e3e6bb42c6172d0f9f895c) to test ansi, unicode, [zero width joiner](https://en.wikipedia.org/wiki/Zero-width_joiner) caracters with some node packages. 
It appears that [string-width](https://www.npmjs.com/package/string-width) is doing a pretty good job as far as string's caracters are not mixed (e.g. '\u001B[1municorn\u001B[22m 🤓 ☆  👶🏽  端').
At the end, it seems to be pretty tricky to get the real length on the screen.

**Comment by cronvel** [comment]
I know how to do it, I just need times for that ;)

**Comment by cronvel** [comment]
@domq @ponsfrilus Made various fixes and improvements, tell me if it works for you! ;)

**Comment by ponsfrilus** [comment]
@cronvel it works very weel, thank you so much ! The new version of [gTrend](https://github.com/ponsfrilus/gtrend) is working like a charm :+1:
