### ISSUE TITLE
Support cancelable for .singleLineMenu and .singleColumnMenu

### ISSUE THREAD

**Issue by hfhchan** [cronvel/terminal-kit#71]
Adding Key event handlers and/or using `exitOnUnexpectedKey` seems like overkill for this (common?) use-case.

**Comment by cronvel** [comment]
Hi, 

Thanks for your input, however I believe that the default use-case is when you want your user to actually SELECT an option. Bypassing the menu is not the default expected behavior.

**Comment by hfhchan** [comment]
The implementer would need to explicitly set `cancelable: true` for the ESC key to take effect.

I am implementing a console application where different screens would be shown depending on the menu behavior, and there needs to provide a way for the user to backtrack instead of CTRL+C and starting over.  Adding a "Back" option to the menu would be less user-friendly.

**Comment by cronvel** [comment]
It's merged, pushed and published on npm as v1.26.3.
Thanks ;)
