### ISSUE TITLE
Closed Automatically At Exporting .exe With pkg

### ISSUE THREAD

**Issue by DiabloRodriguez** [cronvel/terminal-kit#73]
I don't know why, but when I try to export a .exe file with terminal-kit, the .exe file is closed automatically.
How do I know what is caused by terminal-kit?, 'cause When I Retire terminal-kit of my code the exported .exe is working perfectly.

If anyone want to see my code, is here, but I repeat, when I retire "require('terminal-kit')" the .exe works. But in terminal with "node index.js" it's working fine with terminal-kit.

```
var term = require('terminal-kit').terminal;
var User = require('./user.js');

setInterval(function() {
    console.log("timer that keeps nodejs processing running");
}, 1000 * 60 * 60);

console.clear = function(){
	var lines = process.stdout.getWindowSize()[1];
	for(var i = 0; i < lines; i++) {
	    console.log('\r\n');
	}
}

//STARTS LOADING USER Data
User.Load();
if(User.Data.language == null){
	console.clear();
	console.log( 'Select Language:\n' ) ;
	var items = [
		'> English' ,
		'> Spanish'
	] ;

	term.singleColumnMenu( items , function( error , response ) {
		term( '\n' ).eraseLineAfter.green(
			"#%s selected: %s (%s,%s)\n" ,
			response.selectedIndex ,
			response.selectedText ,
			response.x ,
			response.y
		) ;
		process.exit() ;
	} ) ;
}
//========================
```

**Comment by cronvel** [comment]
@DiabloRodriguez What do you mean by "exporting an .exe"? You are working on Windows and use some kind of third party software to build an .exe program? Which runtime is running it?

**Comment by laurent22** [comment]
Maybe an exception due to a file that want packaged? Don't they provide a way to view thrown exceptions?

**Comment by cronvel** [comment]
@DiabloRodriguez Hmm... Since I don't own a Windows, it will be hard for me to debug things... Few questions:
- does *pkg* come with its own terminal rather than the built-in Windows one?
- any error output before quitting?
- which Node version is using your build?

**Comment by DiabloRodriguez** [comment]
@cronvel 

- Basically _pkg_ exports a "console exe", A exe that is opened with Windows Console (CMD).
- No errors, practically nothing, just console open and closes with black screen, no output.
- My Node Version is v8.11.3

I want to add a curiosity, when I add code before add terminal-kit :

> require('terminal-kit).terminal

The code is executing without problems like _console.log('hello')_. But in theory when the .exe run the inclusion of terminal-kit, it closes by itself. No errors, no _.log_ file, 'cause _pkg_ no supports "debug" option in exported file.

I tried with other build option, [nexe](https://www.npmjs.com/package/nexe) is other package that allows to build a exe file. But the same thing happens.

Everything happens in the inclusion of the _terminal-kit_ variable kit

**Comment by DiabloRodriguez** [comment]
I do not know, but in the end I think that for the moment it is impossible to solve it. Just to add, when _pkg_ compiles packages if there are errors it reports them in the compiled process, so if there was a problem with the terminal kit package, _pkg_ would have already said it. The same happens in _nexe_.

**Comment by tvoloshyn** [comment]
@DiabloRodriguez The reason it doesn't work for you is because `pkg` analyses all of the require statements in order to determine what to package. If you look inside the `terminal-kit.js` you will see that there is a self written module called `lazyness` which is responsible for loading and assigning all of the properties to `termkit` object. `pkg` doesn't know how to parse it, therefore it fails to bundle things.

I've tried to modify that file by "manually" assigning require statements instead of using `lazyness` helper functions and also changing part of `image.js` where require statement of `get-pixles` library is being determined at run-time (used `@cronvel/get-pixels`). I've then used `webpack` to bundle everything to one file and then used `pkg` on that one file.

I have to say this library is truly amazing when it comes to development of CLI tools.

**Comment by cronvel** [comment]
@tvoloshyn Thanks for the great explanation! ;)

I implemented lazy-loading to reduce the startup time. Since this lib is also used for lightweight CLI that run only few ms, a startup time as fast as possible is required.

@DiabloRodriguez Is there a way to tell to `pkg` to include some files specifically? If not, can you open an issue on the `pkg` repository?

**Comment by envis10n** [comment]
This is more than likely the issue.
`"pkg": {
    "assets": "node_modules/terminal-kit/**/*"
  }`
Add this to your package.json and try it again.

**Comment by cronvel** [comment]
@envis10n Maybe `node_modules/terminal-kit/lib/**/*` is more appropriate for the path?

**Comment by envis10n** [comment]
I don't know, the one I posted is what I've been using and it works

**Comment by reberthkss** [comment]
i've same problem. Also added the snippet-code menciod by @envis10n . I'm getting the follow message :

> PS E:\cernov-apps\print-server-marines> ./index.exe
> (node:10284) UnhandledPromiseRejectionWarning: Error: Cannot find module './termconfig/xterm.generic.js'
> Require stack:
> - E:\snapshot\print-server-marines\node_modules\terminal-kit\lib\Terminal.js
> - E:\snapshot\print-server-marines\node_modules\terminal-kit\lib\termkit.js
> - E:\snapshot\print-server-marines\selectPrinterMenu.js
> - E:\snapshot\print-server-marines\index.js
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1012:15)
>     at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
>     at Function.Module._load (internal/modules/cjs/loader.js:882:27)
>     at Module.require (internal/modules/cjs/loader.js:1072:19)
>     at Module.require (pkg/prelude/bootstrap.js:1225:31)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.createTerminal (E:\snapshot\print-server-marines\node_modules\terminal-kit\lib\Terminal.js:159:18)
>     at terminal (E:\snapshot\print-server-marines\node_modules\terminal-kit\lib\termkit.js:106:18)
>     at Object.get [as terminal] (E:\snapshot\print-server-marines\node_modules\lazyness\lib\Lazyness.js:48:16)
>     at E:\snapshot\print-server-marines\index.js
> (Use `index --trace-warnings ...` to show where the warning was created)
> (node:10284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:10284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
