### ISSUE TITLE
Error loading under termux on android

### ISSUE THREAD

**Issue by envis10n** [cronvel/terminal-kit#75]
```
terminal-kit/lib/Terminal.js:268:31
TypeError: Cannot read property 'on' of undefined at Object.keys.forEach
```

Was working fine until I updated to the most recent version of terminal-kit. 
Node v11.1.0

**Comment by cronvel** [comment]
@envis10n Hi, I wonder how it can be possible... Can you run `./sample/detect-terminal-test.js` ? Also, can you try-catch the offending line and report the value of the `key` variable?

**Comment by cronvel** [comment]
@envis10n Ok, forget the previous message, just update to v1.26.6, and copy-paste me the error message.

**Comment by envis10n** [comment]
Okay, sorry. My project was clearing after the message was printed. It revealed there is an issue with an array prototype function I was adding (Array.prototype.random). After removing this in favor of a regular function, the issue is gone. This was a recent change on my end.

This issue is not present on windows, but is present on linux.

`using termconfig: 'xterm-256color.generic.js'.`
