### ISSUE TITLE
progressBar feature request

### ISSUE THREAD

**Issue by markrad** [cronvel/terminal-kit#77]
I have a scenario where I would like to 'reset' a progress bar back to zero. Though this works to an extent, it continues to calculate the estimated time of arrival based upon the entire time the progress bar has been active so the initial time gets larger and larger. It would be nice to have a .reset method rather than having to destroy and recreate the progressBar each time.

**Comment by cronvel** [comment]
@markrad Done. Let me now if it does the job.

**Comment by markrad** [comment]
Hi @cronvel,

I works great. Thanks for the super fast turnaround.
