### ISSUE TITLE
Backspace character not erasing input in input field only when tokenHook is provided

### ISSUE THREAD

**Issue by FireCubez** [cronvel/terminal-kit#79]
I have code that looks like this:

```js
textInputField = term.inputField({
    cancelable: true,
    default: "..."
}, (err, text) => {
    // ...
});
```

It works normally. But I wanted to add syntax highlighting, so I added this tokenHook:
```js
(token, isEOF, prevToks, term, config) => {
	var isFirst = prevToks.length === 0;
	var first;
	if(isFirst) {
		first = token;
	} else {
		first = prevToks[0];
	}

	// If we aren't in a command, don't
	// bother with syntax highlighting
	if(first[0] !== "/") return term;
	var cmd = token.slice(1);
	if(!isACommand(cmd) && isFirst) {
		config.style = term.blue;
		return term.red;
	}
	return term;
}
```
When I run this and try to press backspace to erase my input, it doesn't work. It just moves the cursor back without deleting chars. I can then overwrite what I wrote before with other chars

---
Edit: this seems to be happening even for a no-op tokenHook. Also happens for the example provided in the docs

**Comment by FireCubez** [comment]
Seems to be related to [this issue](https://github.com/cronvel/terminal-kit/issues/21), where CTRL-U doesn't actually delete the characters. This time it happens with normal backspace and NOT with CTRL-U

**Comment by cronvel** [comment]
Hi @FireCubez ,
Just to say that I have a tons of work at the moment, I will look into the issue once I have some free time. Maybe the next week.

**Comment by cronvel** [comment]
@FireCubez It's fixed now.
