### ISSUE TITLE
Feature: Emit an event when autocompletion choice is highlighted

### ISSUE THREAD

**Issue by mpdatx** [cronvel/terminal-kit#81]
I want to be able to react to a user navigating to (but not selecting) an autocomplete choice.

**Comment by cronvel** [comment]
@mpdatx The 'highlight' event is now implemented, see the doc: [here](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.inputField), [here](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.singleLineMenu) and [here](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.singleColumnMenu).
