### ISSUE TITLE
TextBuffer should support word-wrapping

### ISSUE THREAD

**Issue by jacksbox** [cronvel/terminal-kit#84]
I'm using code like this to draw information to a TextBuffer and draw the result to the terminal.
Everything works fine, except that the text wrapping isn't correctly applied. As I understand `wrap: true` should correctly wrap the text of the TextBuffer, but it doesn't - am I expecting something wrong?

```
const buffer = new TextBuffer({
      dst: SomeScreenBuffer,
      x: 0,
      y: 0,
      width: 20,
      height: 40,
      wrap: true
    })

buffer.insert('A line which is more than 20 characters long')

buffer.draw()
SomeScreenBuffer.draw()
```

**Comment by cronvel** [comment]
Hi @jacksbox 
I'm affraid but TextBuffer does not support **word-wrapping** at the moment. Only simple non-word aware wrapping is supported.

Outside of TextBuffer, you can wrap using [.wrapColumn](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.wrapColumn).

**Comment by jacksbox** [comment]
@cronvel thanks for the fast answer 😄 I feared this might be the case.
I'm trying to have some ui interface in one section of the terminal (which is handled by screenbuffers) and a normal `log-output` section in the other. Is there a way of doing this with terminal-kit?

**Comment by cronvel** [comment]
If you want something like *tmux*, it's possible but Terminal Kit actually lacks a Virtual Terminal Emulation backed by a ScreenBuffer, which is on my TODO (but no time to code that ATM). You will have to manage your `log-output` on your own.

**Comment by cronvel** [comment]
@jacksbox Now TextBuffer supports word-wrapping through the 'wordWrapWidth' option. But it still not plainly automatic, you have to call `textBuffer.wordWrapAllLines()` whenever you update the content. It will becomes automatic later (it's on my TODO).

**Comment by cronvel** [comment]
@jacksbox Line-wrapping/word-wrapping is now possible and automatic.
For the record, it's not the `wordWrapWidth` option anymore but `lineWrapWidth` (integer), option `wordWrap` (boolean) control if line-wrapping is word-aware or not.
