### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by anemol** [cronvel/terminal-kit#86]
Linux, NodeJS v6.16

```
var term = require( 'terminal-kit' ).terminal ;
```

It gives this error:

```
/home/ciel/Programmation/LWOS/node_modules/terminal-kit/lib/detectTerminal.js:179
exports.getParentTerminalInfo = async function getParentTerminalInfo( callback ) {
                                      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ciel/Programmation/LWOS/node_modules/terminal-kit/lib/termkit.js:53:26)
```
Are there dependencies to install?

**Comment by laurent22** [comment]
async/await was added in NodeJs 8 so you'll need at least this version to get it to work.

**Comment by anemol** [comment]
I must work with Node v6.x. No solution?

**Comment by laurent22** [comment]
I guess you could transpile the lib using Babel, but I've never tried that so I don't know if it would work. Perhaps someone else here could help.

**Comment by cronvel** [comment]
@anemol Sorry, but the lib require Node v8 Carbon LTS. Node v6 reachs end-of-life in exactly [one month](https://nodejs.org/en/about/releases/). Also I'm curious: why **npm** didn't inform you that your node version is is not valid?

If you are stuck with node v6, either use an older version of Terminal-kit, or patch the few occurrences where *async functions* are used, replacing them by *Promises*... or use Babel.

**Comment by cronvel** [comment]
@anemol You can use at most Terminal-kit v1.18.0, which was published on July 2018, so it's not that old.
I have made a mistake, I only changed the node engine version in the `package.json` on v1.26.4, but in fact node v8 in mandatory for all v1.19+ version.
I have updated the CHANGELOG accordingly.

**Comment by anemol** [comment]
Thank, i will try the previous version. :)
