### ISSUE TITLE
Add method to set fg/bg color by name

### ISSUE THREAD

**Issue by tyrak** [cronvel/terminal-kit#87]
I sometimes find myself writing code like this

    if (color === "red")
    	term.red(msg)
    else if (color === "green")
    	term.green(msg)
    else if (color === "yellow")
    	term.yellow(msg)
    else
    	term(msg);

Wouldn't it make sense to have a method, say `.color(...)`, so that I could write:

    term.color(color, msg);

instead of the above.

More formally, the expression

    term.red(...args);

should be equivalent to

    term.color("red", ...args);

The supported colors should be the same as the ones for which there is a method.

Is there a way to do that already and I've overlooked it?

**Comment by cronvel** [comment]
Hi @tyrak ,
Why just `term[color](...args)` ?

Not sure if it would help, but you can also write in red using the `^` markup: `term('^RArgh...')` would write *'Argh...'* in red.

**Comment by tyrak** [comment]
> Why not just `term[color](...args)` ?

I feel that this is slightly dangerous because `color` might be something like `"clear"`.

> Not sure if it would help, but you can also write in red using the `^` markup: `term('^RArgh...')` would write _'Argh...'_ in red.

In my actual code, the string that I'm printing (`msg` in the above example) comes from an untrusted source, so I actually use `term.noFormat.red(...)` which precludes using markup.

**Comment by cronvel** [comment]
@tyrak `term.color()` exists, but it requires an integer (0..15).
I can make a little patch for that if you want.

**Comment by cronvel** [comment]
@tyrak Ok it's done, as of Terminal Kit v1.28.0 `.color()` and `.bgColor()` now accepts color names.
