### ISSUE TITLE
Create a persistent menu

### ISSUE THREAD

**Issue by WeslleyNasRocha** [cronvel/terminal-kit#88]
Im trying to create a persistent menu that the user can choose the options and come back to it

how can i made it with this library?

**Comment by cronvel** [comment]
@WeslleyNasRocha Can you describe that menu a bit more?

**Comment by WeslleyNasRocha** [comment]
It's like a 'main menu'.
When i select an option it executes a function but at the end, it comes back to the 'main menu'

Ex.
prints main menu
```
Say my name
Knock knock
Exit
```
Select option 2 - `Knock Knock` and execute an function

```
I'm the one who knocks
```
And then come back to the main menu

```
Say my name
Knock knock
Exit
```

**Comment by cronvel** [comment]
@WeslleyNasRocha Ok, sorry my question was unclear. I wanted to know about the item disposition. You want a vertical menu, right? If so: use the [single column menu](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.singleColumnMenu). Turn the `continueOnSubmit` option on.

**Comment by WeslleyNasRocha** [comment]
i got it with the sample `async menu` wrapped in an `while(true)`
```javascript
async function asyncMenu() {

    while (true) {
      var response = await term.singleColumnMenu(items).promise;

      term.green(
        '\n#%s %s: %s (%s,%s)\n',
        response.selectedIndex,
        response.submitted ? 'submitted' : 'selected',
        response.selectedText,
        response.x,
        response.y,
      );
    }
  }
```

Thanks.

Great library by the way ;)
