### ISSUE TITLE
32 bits (RGBA) color in ScreenBuffer?

### ISSUE THREAD

**Issue by spywhere** [cronvel/terminal-kit#9]
Will ScreenBuffer supports 24 bits color? If already supports, how? I can't find a code that use 24 bits color in a  spaceship demo.

**Comment by cronvel** [comment]
Hi, 

There is no 24bits support for the ScreenBuffer at the moment.

It's one of the feature I would like to see in the future, but there are lot of things in my TODO with higher priority (e.g. full-width chars support).

But now I'm curious: what kind of app are you building? ^^

**Comment by spywhere** [comment]
I'm currently working on CLI-based UI kit right now. Here's the repo if you want to check it out: https://github.com/spywhere/cuikit

**Comment by cronvel** [comment]
It looks really promising!

From a scale from 0 to 10, how much do you need 24bits ScreenBuffer?

**Comment by spywhere** [comment]
Currently 8 bits color would work, but 24 bits color will allows the user to customize their application much more colorful. I would give 3/10 for now since the framework itself still under development too.

**Comment by cronvel** [comment]
@spywhere Are you still writing your lib? I just released a version featuring 32-bit ScreenBuffer with composition. Still in beta, but the API should not change unless proven wrong.

You may want to run `./sample/screenbuffer-hd-test.js`.

I screwed up the commit message, it's not 24-bit, but 32-bit (RGBA).

**Comment by cronvel** [comment]
@spywhere Now it's even possible to load image (PNG, JPEG and GIF).

**Comment by spywhere** [comment]
So far, I think this issue can be close now as this already fulfil my need. Thanks for your work.
