### ISSUE TITLE
singleLineMenu highlight event returns highlightIndex for current page

### ISSUE THREAD

**Issue by ahutchinson1** [cronvel/terminal-kit#90]
For singleLineMenu, the submit "event" returns a 'selectedIndex' value based on the entire item list (rather than the current page), and I think this is correct behavior. But the highlight event returns a 'highlightedIndex' value for the current page, making it difficult (or impossible?) to know the highlighted item if you are not on the first page of the item list.

**Comment by cronvel** [comment]
@ahutchinson1 There is no sign in the doc or in the code comment that it would be the wanted behavior, so this is definitively a bug. You are right, it makes no sense.
It's fixed as of v1.28.1.
Thanks for reporting it and for your patience! ;)

**Comment by ahutchinson1** [comment]
@cronvel Yes, works perfectly now! Thank you :)
