### ISSUE TITLE
Unable to use terminal kit starting from 1.29.1

### ISSUE THREAD

**Issue by roman-petrov** [cronvel/terminal-kit#95]
When trying to upgrade terminal kit to 1.29.2 I am immediately getting an unhanded exception when creating `terminal-kit` instance in my program. Here is a screenshot:

![image](https://user-images.githubusercontent.com/18419515/62410310-a7954e00-b5ec-11e9-9ac8-6fb09e176bc7.png)

I tried to investigate the problem and found that `defaultColorRegister` variable contains some values where some RGB components are greater than `255` so `registerForRgb` function throws an exception on these values.

`defaultColorRegister` is being filled in `buildDefaultColorRegister ` function and the algorithm can produce values greater than 255.

https://github.com/cronvel/terminal-kit/blob/master/lib/Terminal.js#L1608

For example, for `offset=31` it will give green value `( ( 31 / 6 ) % 6 ) * 51 = 263.5`.

I am not familiar with logic in this method so I don't know how to make a `PR`, can you please help with this?

Many thanks!

**Comment by laurent22** [comment]
We have the same error in Joplin: https://github.com/laurent22/joplin/issues/1778

**Comment by cronvel** [comment]
@roman-petrov @laurent22 I will investigate it right now. 
BTW, did you get that on v1.29.2 which is the latest version?

**Comment by cronvel** [comment]
@roman-petrov @laurent22 Ok, it should be fixed now as of v1.29.3. Thanks for reporting it.
I have done a lot of work on Terminal-Kit recently, and I overlooked this one. I should investigate on the *why it didn't manifest on my side*.

**Comment by roman-petrov** [comment]
@cronvel, thank you very much for such a quick help! everything is working as expected now, I am closing this issue.
