### ISSUE TITLE
Using a tokenRegExp of /./ causes an infinite loop

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cronvel/terminal-kit#97]
For instance, with the following:

```javascript
   term.inputField(
      {
         tokenRegExp: /./,
         tokenHook: function(token, isEndOfInput, previousTokens, term, config) {
            // no-op
         },
      },
      function(){}
   )
```

I get an input field, but as soon as a single character is entered, that character is printed forever, over and over, in an infinite loop:

<img width="897" alt="Screen Shot 2019-08-31 at 22 55 22" src="https://user-images.githubusercontent.com/200/64071563-7a1adf00-cc42-11e9-90bf-42caad900c32.png">

(For context: I'm basically trying to do the equivalent of `term.on('key', ...)` during a user's interaction with a `term.inputField()`, but I need to maintain access to the *current value* they've typed in so far, which the `'key'` event obviously can't provide. The closest I seem to be able to get is to use `tokenHook` with a single-character regex, and use `previousTokens.join('')` to access the input-so-far ... not pretty, but I can't think of a better way to maintain realtime access to the user's input.)

**Comment by cronvel** [comment]
@ELLIOTTCABLE Your regexp must have the 'g' flag, also I should update the doc to say so, or throw an error if it's not the case.

**Comment by cronvel** [comment]
@ELLIOTTCABLE The doc is fixed, and it throws when the 'g' flag is missing as of v1.31.2. Thanks for reporting! ;)

By the way using the token hook is not the correct way to do what you want. You should use the 'key' event, and use the `input.getInput()` to retrieve the actual value, where `input = term.inputField()`.

**Comment by ELLIOTTCABLE** [comment]
<3

Ahhah! I didn't see the return-value of `getInput()` there; that's a much better idea. That said, I ended up ‘upgrading’ to a full `TextBuffer` instead; and it's working pretty well so far for my use-case.

Great library; keep up the good work! (And maybe consider upstreaming the types from #62 so you can keep them in sync; they're pretty badly out-of-sync by now! 😫)
