### ISSUE TITLE
Is there a way to show a spinner of some sort?

### ISSUE THREAD

**Issue by bjdash** [cronvel/terminal-kit#98]
Is there a way to show a spinner of some sort?

**Comment by cronvel** [comment]
Hi @bjdash ,
No, there is no stand-alone spinner at the moment, however there is a nice [progress bar](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.progressBar) that eventually display a spinner as long as the ETA is undefined.

**Comment by cronvel** [comment]
@bjdash As of v1.37.0, spinner are supported, see the doc [here](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.spinner).

**Comment by bjdash** [comment]
Awesome.
